//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 2.0.5.0
// 
namespace CallDataBaseDemo.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://tempuri.org/")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string UIDField;
        
        private string UNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UName {
            get {
                return this.UNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UNameField, value) != true)) {
                    this.UNameField = value;
                    this.RaisePropertyChanged("UName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(CallDataBaseDemo.ServiceReference1.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        CallDataBaseDemo.ServiceReference1.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SelectUserInfo", ReplyAction="*")]
        System.IAsyncResult BeginSelectUserInfo(CallDataBaseDemo.ServiceReference1.SelectUserInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        CallDataBaseDemo.ServiceReference1.SelectUserInfoResponse EndSelectUserInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Yes", ReplyAction="*")]
        System.IAsyncResult BeginYes(System.AsyncCallback callback, object asyncState);
        
        void EndYes(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public CallDataBaseDemo.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CallDataBaseDemo.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public CallDataBaseDemo.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CallDataBaseDemo.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public CallDataBaseDemo.ServiceReference1.SelectUserInfoRequestBody Body;
        
        public SelectUserInfoRequest() {
        }
        
        public SelectUserInfoRequest(CallDataBaseDemo.ServiceReference1.SelectUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectUserInfoRequestBody {
        
        public SelectUserInfoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CallDataBaseDemo.ServiceReference1.SelectUserInfoResponseBody Body;
        
        public SelectUserInfoResponse() {
        }
        
        public SelectUserInfoResponse(CallDataBaseDemo.ServiceReference1.SelectUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<CallDataBaseDemo.ServiceReference1.UserInfo> SelectUserInfoResult;
        
        public SelectUserInfoResponseBody() {
        }
        
        public SelectUserInfoResponseBody(System.Collections.ObjectModel.ObservableCollection<CallDataBaseDemo.ServiceReference1.UserInfo> SelectUserInfoResult) {
            this.SelectUserInfoResult = SelectUserInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WebService1SoapChannel : CallDataBaseDemo.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SelectUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<CallDataBaseDemo.ServiceReference1.UserInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<CallDataBaseDemo.ServiceReference1.UserInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<CallDataBaseDemo.ServiceReference1.WebService1Soap>, CallDataBaseDemo.ServiceReference1.WebService1Soap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginSelectUserInfoDelegate;
        
        private EndOperationDelegate onEndSelectUserInfoDelegate;
        
        private System.Threading.SendOrPostCallback onSelectUserInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginYesDelegate;
        
        private EndOperationDelegate onEndYesDelegate;
        
        private System.Threading.SendOrPostCallback onYesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<SelectUserInfoCompletedEventArgs> SelectUserInfoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> YesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CallDataBaseDemo.ServiceReference1.WebService1Soap.BeginHelloWorld(CallDataBaseDemo.ServiceReference1.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            CallDataBaseDemo.ServiceReference1.HelloWorldRequest inValue = new CallDataBaseDemo.ServiceReference1.HelloWorldRequest();
            inValue.Body = new CallDataBaseDemo.ServiceReference1.HelloWorldRequestBody();
            return ((CallDataBaseDemo.ServiceReference1.WebService1Soap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallDataBaseDemo.ServiceReference1.HelloWorldResponse CallDataBaseDemo.ServiceReference1.WebService1Soap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndHelloWorld(System.IAsyncResult result) {
            CallDataBaseDemo.ServiceReference1.HelloWorldResponse retVal = ((CallDataBaseDemo.ServiceReference1.WebService1Soap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CallDataBaseDemo.ServiceReference1.WebService1Soap.BeginSelectUserInfo(CallDataBaseDemo.ServiceReference1.SelectUserInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectUserInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSelectUserInfo(System.AsyncCallback callback, object asyncState) {
            CallDataBaseDemo.ServiceReference1.SelectUserInfoRequest inValue = new CallDataBaseDemo.ServiceReference1.SelectUserInfoRequest();
            inValue.Body = new CallDataBaseDemo.ServiceReference1.SelectUserInfoRequestBody();
            return ((CallDataBaseDemo.ServiceReference1.WebService1Soap)(this)).BeginSelectUserInfo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallDataBaseDemo.ServiceReference1.SelectUserInfoResponse CallDataBaseDemo.ServiceReference1.WebService1Soap.EndSelectUserInfo(System.IAsyncResult result) {
            return base.Channel.EndSelectUserInfo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<CallDataBaseDemo.ServiceReference1.UserInfo> EndSelectUserInfo(System.IAsyncResult result) {
            CallDataBaseDemo.ServiceReference1.SelectUserInfoResponse retVal = ((CallDataBaseDemo.ServiceReference1.WebService1Soap)(this)).EndSelectUserInfo(result);
            return retVal.Body.SelectUserInfoResult;
        }
        
        private System.IAsyncResult OnBeginSelectUserInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginSelectUserInfo(callback, asyncState);
        }
        
        private object[] OnEndSelectUserInfo(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<CallDataBaseDemo.ServiceReference1.UserInfo> retVal = this.EndSelectUserInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectUserInfoCompleted(object state) {
            if ((this.SelectUserInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectUserInfoCompleted(this, new SelectUserInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectUserInfoAsync() {
            this.SelectUserInfoAsync(null);
        }
        
        public void SelectUserInfoAsync(object userState) {
            if ((this.onBeginSelectUserInfoDelegate == null)) {
                this.onBeginSelectUserInfoDelegate = new BeginOperationDelegate(this.OnBeginSelectUserInfo);
            }
            if ((this.onEndSelectUserInfoDelegate == null)) {
                this.onEndSelectUserInfoDelegate = new EndOperationDelegate(this.OnEndSelectUserInfo);
            }
            if ((this.onSelectUserInfoCompletedDelegate == null)) {
                this.onSelectUserInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectUserInfoCompleted);
            }
            base.InvokeAsync(this.onBeginSelectUserInfoDelegate, null, this.onEndSelectUserInfoDelegate, this.onSelectUserInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CallDataBaseDemo.ServiceReference1.WebService1Soap.BeginYes(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginYes(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CallDataBaseDemo.ServiceReference1.WebService1Soap.EndYes(System.IAsyncResult result) {
            base.Channel.EndYes(result);
        }
        
        private System.IAsyncResult OnBeginYes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CallDataBaseDemo.ServiceReference1.WebService1Soap)(this)).BeginYes(callback, asyncState);
        }
        
        private object[] OnEndYes(System.IAsyncResult result) {
            ((CallDataBaseDemo.ServiceReference1.WebService1Soap)(this)).EndYes(result);
            return null;
        }
        
        private void OnYesCompleted(object state) {
            if ((this.YesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.YesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void YesAsync() {
            this.YesAsync(null);
        }
        
        public void YesAsync(object userState) {
            if ((this.onBeginYesDelegate == null)) {
                this.onBeginYesDelegate = new BeginOperationDelegate(this.OnBeginYes);
            }
            if ((this.onEndYesDelegate == null)) {
                this.onEndYesDelegate = new EndOperationDelegate(this.OnEndYes);
            }
            if ((this.onYesCompletedDelegate == null)) {
                this.onYesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnYesCompleted);
            }
            base.InvokeAsync(this.onBeginYesDelegate, null, this.onEndYesDelegate, this.onYesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CallDataBaseDemo.ServiceReference1.WebService1Soap CreateChannel() {
            return new WebService1SoapClientChannel(this);
        }
        
        private class WebService1SoapClientChannel : ChannelBase<CallDataBaseDemo.ServiceReference1.WebService1Soap>, CallDataBaseDemo.ServiceReference1.WebService1Soap {
            
            public WebService1SoapClientChannel(System.ServiceModel.ClientBase<CallDataBaseDemo.ServiceReference1.WebService1Soap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloWorld(CallDataBaseDemo.ServiceReference1.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public CallDataBaseDemo.ServiceReference1.HelloWorldResponse EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                CallDataBaseDemo.ServiceReference1.HelloWorldResponse _result = ((CallDataBaseDemo.ServiceReference1.HelloWorldResponse)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSelectUserInfo(CallDataBaseDemo.ServiceReference1.SelectUserInfoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SelectUserInfo", _args, callback, asyncState);
                return _result;
            }
            
            public CallDataBaseDemo.ServiceReference1.SelectUserInfoResponse EndSelectUserInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                CallDataBaseDemo.ServiceReference1.SelectUserInfoResponse _result = ((CallDataBaseDemo.ServiceReference1.SelectUserInfoResponse)(base.EndInvoke("SelectUserInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginYes(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Yes", _args, callback, asyncState);
                return _result;
            }
            
            public void EndYes(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Yes", _args, result);
            }
        }
    }
}
