if(typeof(_10powertalk_load_service) == 'undefined' || !_10powertalk_load_service)
{
var _10powertalk_load_service =true;

eval("function $10powertalk_get(obj){var element = null;if(document.getElementById){element = document.getElementById(obj);}else if(document.all){element = document.all[obj];}else if(document.layers){element = document.layers[obj];}return element; }");
eval( "function _10powertalk_GetCookieVal(offset){  var endstr = document.cookie.indexOf(\";\",offset);  if (endstr==-1)  endstr=document.cookie.length;  return unescape(document.cookie.substring(offset,endstr)); }" ); 
eval("function _10powertalk_GetCookie(name) { var arg=name+\"=\";  var alen=arg.length; var clen=document.cookie.length; var i=0;  while(i< clen) { var j=i+alen; if(document.cookie.substring(i,j)==arg) return _10powertalk_GetCookieVal(j);  i=document.cookie.indexOf(\" \",i) + 1; if(i==0)break; } return null; }" ); 
eval("function _10powertalk_SetCookie(name, value){ var expdate = new Date(); var argv = _10powertalk_SetCookie.arguments;  var argc = _10powertalk_SetCookie.arguments.length;  var expires = (argc > 2) ? argv[2] : null;  var path = (argc > 3) ? argv[3] : null;  var domain = (argc > 4) ? argv[4] : null;  var secure = (argc > 5) ? argv[5] : false;  if(expires!=null) expdate.setTime(expdate.getTime() + ( expires * 1000 )); document.cookie = name + \"=\" + escape (value) +((expires == null) ? \"\" : (\"; expires=\"+ expdate.toGMTString()))  +((path == null) ? \"\" : (\"; path=\" + path)) +((domain == null) ? \"\" : (\"; domain=\" + domain))  +((secure == true) ? \"; secure\" : \"\"); } ");
var _10powertalk_ClientID;
var _10powertalk_MSNPassport ='';
var _10powertalk_host = 'http://www.powertalkbox.cn/'; 
var _10powertalk_settings = 'mw7mN6I6wIz3Amz3Amm6mmXm';
var _10powertalk_NewGuid = 'ac2e33f5-f1f0-403f-bf41-3d0357940233';
eval( "_10powertalk_ClientID=_10powertalk_GetCookie(\"_10powertalk_ClientID\");  if(_10powertalk_ClientID==null || _10powertalk_ClientID==\"\"){ _10powertalk_ClientID=_10powertalk_NewGuid; _10powertalk_SetCookie(\"_10powertalk_ClientID\",_10powertalk_ClientID,365*24*60*60*1000);}" );eval( "function _10powertalk_GetSystemName(){var sReturn=navigator.userAgent.toLowerCase();var sWin='Windows ';try { if (sReturn.indexOf('win')!=-1) {if((sReturn.indexOf('nt')!=-1) && (sReturn.indexOf('5.2')!=-1)) return(sWin+'2003');if((sReturn.indexOf('nt')!=-1) && (sReturn.indexOf('5.1')!=-1)) return(sWin+'XP');if((sReturn.indexOf('nt')!=-1) && (sReturn.indexOf('5.0')!=-1)) return(sWin+'2000');if (sReturn.indexOf('nt')!=-1) return(sWin+'NT 4.0');if((sReturn.indexOf('98')!=-1) && (sReturn.indexOf('9x')!=-1)) return(sWin+'Me');if (sReturn.indexOf('98')!=-1) return(sWin+'98');if (sReturn.indexOf('95')!=-1) return(sWin+'95');}if(sReturn.indexOf('IRIX')!=-1) return('Irix');if(sReturn.indexOf('Mac')!=-1) return('Macintosh');}catch (er){var sReturn='unknown';} return sReturn;}");
eval( "function _10powertalk_GetBrowserName(){var sReturn=navigator.appVersion;var SPeXt=(navigator.userAgent.indexOf(\"Opera\")!=-1 && navigator.userAgent.indexOf(\"5.\")>0) ? \"op\" : (document.all) ? \"ie\" : (document.layers) ? \"nn\" : (!document.all && document.getElementById) ? \"mo\":\"\";var arrVersion=sReturn.split(\"[\");if (SPeXt==\"op\"){arrVersion=sReturn.split(\"(\");arrVersion[1]=\"Opera \"+arrVersion[0];}sInfo=sReturn.split(\"; \");if(SPeXt==\"mo\"){nnbrws=navigator.userAgent.split(\"; \");if (nnbrws[4]) if (nnbrws[4].match(\"Netscape\")){nnbrws=nnbrws[4].split(\"Netscape\");sInfo[1]=\"Netscape\"+nnbrws[1];} else{nnbrws=nnbrws[4].split(\")\");sInfo[1]=\"Mozilla\"+nnbrws[0];}}if (SPeXt==\"ie\" || SPeXt==\"mo\") return(sInfo[1]);else return(navigator.appName+' '+arrVersion[0]);return(navigator.appName+sReturn);}");eval( "function _10powertalk_GetMSNPassport(){try{var msn=new ActiveXObject(\"Messenger.UIAutomation\");MSNStatus=msn.MyStatus;var oService = msn.Services;var oPrimserv = oService.P;var oPrimserv = oService.PrimaryService;var MSNPassport=oPrimserv.MySigninName;return MSNPassport;}catch(e){return \"\";}}_10powertalk_MSNPassport=_10powertalk_GetMSNPassport();");
eval( "function _10powertalk_GetBaseData(onlyLoc){var loc=window.location.href;var ref=document.referrer;var data;if(window.parent!=null){if(window.parent.location!=null)loc = window.parent.location.href;if(window.parent.document.referrer!=null)ref = window.parent.document.referrer;}data='&loc='+escape(loc)+'&ref='+escape(ref)+'&res='+escape(window.screen.width+'*'+window.screen.height)+'&color='+screen.colorDepth+'&language='+escape(window.navigator.systemLanguage?window.navigator.systemLanguage:window.navigator.language)+'&os='+escape(_10powertalk_GetSystemName())+'&browser='+escape(_10powertalk_GetBrowserName());return data;}");eval( "function _10powertalk_openChatWin(host, settings, UserID, language){var url = host + \"chat/VIPChatWin.aspx?settings=\" + settings + \"&ClientID=\" + _10powertalk_ClientID +  \"&msn=\"+escape(_10powertalk_MSNPassport) + _10powertalk_GetBaseData(true);if(UserID) url += \"&UserID=\" + UserID.toString();if(language && language.length > 0 ) url += \"&LL=\" + language;window.open( url, settings + \"0\" ,\"width=670,height=570, toolbar=no, menubar=no, scrollbars=no, resizable=yes,location=no, status=no,center=yes\")}");eval("function _10powertalk_applyScript(host,uID, CallCount, AccountID, UserID ){var url = host + \"chat/applyStatus.aspx?uID=\" + uID + \"&CallCount=\" + CallCount.toString() + \"&AccountID=\" + AccountID + \"&UserID=\" + UserID + \"&timeStamp=\" + new Date().getTime().toString();var o_js_obj=$10powertalk_get(\"_10powertalk_applyScript\"); if(o_js_obj)o_js_obj.parentNode.removeChild(o_js_obj);var js_obj = document.createElement( \"script\" );js_obj.type = \"text/javascript\" ;js_obj.setAttribute( \"src\" , url);js_obj.setAttribute(\"id\",\"_10powertalk_applyScript\"); document.body.appendChild(js_obj); }");
var _10powertalk_l_language='';
var _10powertalk_l_icon_width = 100;
var _10powertalk_l_icon_padding = 20;
var _10powertalk_l_icon_top = 300;
var _10powertalk_l_ifInvite = 0;
var _10powertalk_l_icon_hide = 0;
var _10powertalk_l_inviteWay = 0;
var _10powertalk_Invite_UserID = 0; 
var _10powertalk_Invite_Send = 0;
var _10powertalk_have_closed = 0; 
var _10powertalk_Inner_Cont = '';
var _10powertalk_Inner_Invite = '';
var _10powertalk_AccountID = '9';
var _10powertalk_UserID = '1';

document.writeln( '<script ' + ' language=JavaScript src="float.js"></scr'+'ipt>'); 
var _10powertalk_l_icon_align = "left";
var _10powertalk_l_icon_valign = "top";
var _10powertalk_l_invite_width = 402; 
var _10powertalk_l_invite_padding = 300;
var _10powertalk_l_invite_top = 200;
var _10powertalk_l_invite_align = "left";
var _10powertalk_l_invite_valign = "top";

document.writeln( "<div id=\"_10powertalk_Invite_container\"></div>" ); 
_10powertalk_Inner_Invite = "<div style=\"POSITION: absolute; width: auto; height: auto; border: 0;  Z-INDEX: 8000; display: none; OVERFLOW: hidden; \"  id=\"_10powertalk_inviteIcon\"><table width=\"402\" height=\"142\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" class=\"call365_form_invite\" > <tr><td valign=\"top\"><table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tr><td align=\"center\" class=\"th_floatList_02\"><table width=\"99%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tr><td width=\"16\" align=\"left\"><img src=\"menugif/008.gif\" width=\"12\" height=\"15\"></td><td align=\"left\"><span id=\"spanTitle1\">欢迎咨询</span></td> <td width=\"15\"><a href=\"javascript:void(0)\" onMouseDown=\"javascript:_10powertalk_hideInvite();\" ><img title=\"close\" src=\"menugif/001.gif\" width=\"8\" height=\"8\" border=\"0\"></a></td></tr></table>            </td></tr><tr><td height=\"119\" class=\"td_floatList_02\"><table width=\"99%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tr><td width=\"70\" height=\"86\" valign=\"top\"><table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tr><td height=\"6\"><img src=\"menugif/noimage.gif\" width=\"1\" height=\"1\"></td></tr></table><table width=\"70\" height=\"69\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"menugif/011.gif\"><tr><td align=\"center\" valign=\"middle\"><img id=\"imgHead1\" src=\"\" width=\"59\" height=\"59\" /></td></tr></table></td><td align=\"center\" valign=\"top\"><table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tr><td height=\"15\"><img src=\"menugif/noimage.gif\" width=\"1\" height=\"1\"></td></tr></table><table width=\"95%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tr><td height=\"33\" align=\"left\" valign=\"middle\" class=\"contentheading_floatList_04\"> <span id=\"spanCont1\">您好！如有问题请点击在线咨询</span></td></tr><tr><td height=\"58\" align=\"right\" valign=\"bottom\"><span id=\"_10powertalk_invite_button\" onclick=\"javascript:_10powertalk_openChatWin(_10powertalk_host,'mw7mN6I6wIz3Amz3Amm6mmXm', _10powertalk_Invite_UserID, _10powertalk_l_language ); _10powertalk_hideInvite();\" ><img src=\"menugif/012.gif\" width=\"71\" height=\"19\" border=\"0\" /></span>&nbsp;&nbsp;&nbsp;<a href=\"javascript:void(0)\" onMouseDown=\"javascript:_10powertalk_hideInvite();\" ><img src=\"menugif/013.gif\" width=\"71\" height=\"19\" border=\"0\" /></a></td></tr></table></td></tr></table></td></tr></table></td></tr></table> </div>"; 
document.writeln( "<style type=\"text/css\">  <!--  .contentheading_floatList { font-family: \"宋体\"; font-size: 12px; color: #000000; text-decoration: none; line-height: 22px; font-weight: normal; text-indent: 4pt; } .contentheading_floatList_03 { font-family: \"宋体\"; font-size: 12px; color: #0088E4; text-decoration: none; line-height: 22px; font-weight: normal; } .contentheading_floatList_04 { font-family: \"宋体\"; font-size: 12px; color: #000000; text-decoration: none; line-height: 22px; font-weight: bold; }  .form_floatList_01 { background-color: #fff;} .row_floatList_0 { background:#fff; }  .call365_form_floatlist { background-color:#7489A5; }  .call365_form_floatlist .form_floatList_02{ background-color:#CBDFFA; }  .call365_form_floatlist .th_floatList{ background:url(menugif/002.gif); padding:3px 0; color:#151515; font-weight:bold; font-family: \"宋体\"; text-indent: 4pt; line-height: 15px; font-size: 12px; }  .call365_form_floatlist .th_floatList_01{ background:url(menugif/003.gif); padding:3px 0; color:#0880AE; font-weight:bold; font-family: \"宋体\"; text-indent: 4pt; line-height: 15px; font-size: 12px; }  .call365_form_floatlist .th_floatList_02{ background:url(menugif/002_ADCEF8_1.gif); padding:3px 0; color:#151515; font-weight:bold; font-family: \"宋体\"; text-indent: 4pt; line-height: 15px; font-size: 12px; }  .call365_form_floatlist .td_floatList{ background:#EFF5FD; }  .call365_form_floatlist .td_floatList_02{ background:url(menugif/002_ADCEF8_0.gif); }  -->  </style>");
document.writeln( "<div id=\"_10powertalk_Icon_container\"></div>" ); 
_10powertalk_Inner_Cont = "<div style=\"POSITION: absolute; width: auto; height: auto; border: 0;  Z-INDEX: 8000; display: none; OVERFLOW: hidden; \"  id=\"_10powertalk_serviceIcon\"><table width=\"120\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" class=\"call365_form_floatlist\" >  <tr><td align=\"center\" class=\"td_floatList\"> <table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tr><td height=\"8\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"263\"> <tr> <td style=\"width: 263px; height: 116px; background-image: url(menugif/kefu.jpg);\" align=\"right\" valign=\"bottom\" ><input id=\"ljzxkffffff\" type=\"button\" onclick=\"window.open('IM/Chat.aspx','','width=650,height=489');javascript:_10powertalk_hidePanel();\"  value=\"接受\" style=\"background-color: #99CC00;	background-image: url(menugif/bg_PTSbutton.gif);	background-repeat: repeat-x;	border: 1px solid #003333;	height: 22px;	padding-top: 2px;	padding-right: 0px;	padding-bottom: 0px;	padding-left: 0px;	color: #330000;\" />&nbsp;&nbsp;&nbsp; <input id=\"hlzxkffffff\" type=\"button\" onclick=\"javascript:_10powertalk_hidePanel();\" value=\"忽略\" style=\"background-color: #99CC00;	background-image: url(menugif/bg_PTSbutton.gif);	background-repeat: repeat-x;	border: 1px solid #003333;	height: 22px;	padding-top: 2px;	padding-right: 0px;	padding-bottom: 0px;	padding-left: 0px;	color: #330000;\"/>&nbsp;</td></tr></table></td></tr></table> </td> </tr> </table></td> </tr> </table> </div>";
document.writeln( '<script ' + ' language=JavaScript src="floatLoad.js"></scr'+'ipt>');


}