if(top.location!=self.location)top.location=self.location;
(function(a){a.func={isStrictMode:function(){return document.compatMode!="BackCompat"},pageWidth:function(){return this.isStrictMode()?Math.max(document.documentElement.scrollWidth,document.documentElement.clientWidth):Math.max(document.body.scrollWidth,document.body.clientWidth)},pageHeight:function(){return this.isStrictMode()?Math.max(document.documentElement.scrollHeight,document.documentElement.clientHeight):Math.max(document.body.scrollHeight,document.body.clientHeight)},winWidth:function(){return this.isStrictMode()?
document.documentElement.clientWidth:document.body.clientWidth},winHeight:function(){return this.isStrictMode()?document.documentElement.clientHeight:document.body.clientHeight},isBlank:function(c){return/^\s*$/.test(c)},isEmail:function(c){return/^[A-Z_a-z0-9-\.]+@([A-Z_a-z0-9-]+\.)+[a-z0-9A-Z]{2,4}$/.test(c)},isNumber:function(c){return/^\d+$/.test(c)},isString:function(c){return typeof c=="string"},isMobile:function(c){return/^((\(\d{2,3}\))|(\d{3}\-))?((1[345]\d{9})|(18\d{9}))$/.test(c)},isZip:function(c){return/^[1-9]\d{5}$/.test(c)},
strLen:function(c){function e(b){return/[\u4E00-\uFA29]|[\uE7C7-\uE7F3]/.test(b)}var g=0;for(i=0;i<c.length;i++)g+=e(c.charAt(i))==true?2:1;return g}}})(jQuery);
(function(a){function c(g,b){function d(){setTimeout(function(){a(f).hide();a(f).height(a.func.pageHeight());a(f).width(a.func.pageWidth());a(f).show()},0)}g=g||0.3;b=b||2E3;var f=a("<div>");e=f;a(f).css({position:"absolute",top:0,left:0,opacity:g,background:"#000","z-index":b}).html('<iframe width="100%" height="100%" frameBorder="0" style="position:absolute;top:0;left:0;z-index:1;"></iframe><div style="position:absolute;top:0;left:0;width:100%;height:100%;background-color:#000000;z-index:2;"></div>');d();
a(window).bind("resize",function(){if(e&&a(e).css("display")!="none")try{d()}catch(h){}});a("body").prepend(e)}var e=null;a.DOM={disable:function(g){e||c();g&&a(document.body).css("overflow","hidden")},enable:function(){if(e){e.remove();a(document.body).css("overflow","");e=null}}}})(jQuery);
(function(a){var c=1E4;a.dialog=function(b){this.options=a.extend({left:null,top:null,offsetX:0,offsetY:0,width:400,height:"auto",lock:false,overlay:false,closeButton:false,HTML:"",useIframeInIE6:true,clickClose:true,fade:true,scrollCenter:false,onHide:function(){}},b);var d=this;this.container=a("<div>");this.frame=a("<div>");this.frame.append(this.container);a(document.body).prepend(this.frame);a(this.frame).css({position:"absolute",top:-9999,left:-9999,"z-index":c++,width:this.options.width,height:this.options.height});
if(a.browser.msie&&this.options.useIframeInIE6){b=a("<iframe></iframe>").attr("frameborder",0).attr("scrolling","no").css({position:"absolute",top:0,left:0,"z-index":-1,border:0,opacity:0,width:"100%",height:"100%"});this.frame.append(b);this._iframe=b}this.options.HTML!=""?a(this.container).append(this.options.HTML):a(this.container).append(this.buildDOM);this.dialogContainer=a("#ui_dialog_container").removeAttr("id");this.header=a("#ui_dialog_header").removeAttr("id");this.body=a("#ui_dialog_body").removeAttr("id");
this.footer=a("#ui_dialog_footer").removeAttr("id");this.closeButton=a("#ui_dialog_close").removeAttr("id");this.header.hide=function(){a(this).hide();return d};this.footer.hide=function(){a(this).hide();return d};this.options.closeButton?a(this.closeButton).click(function(){d.hide()}):a(this.closeButton).hide();this._hotKeyEvent=function(f){f=f||window.event;code=f.keyCode;code=="27"&&d.hide()};a(document).bind("keyup",d._hotKeyEvent);this._clickClose=function(f){f.button!=2&&d.hide()};this._scrollCenter=
function(){setTimeout(function(){d.refresh()},100)}};a.dialog.prototype={header:null,body:null,footer:null,_iframe:null,_buttons:[],buildDOM:function(){return'<table id="ui_dialog_container" style="width: 100%; height: 100%;" class="pop_dialog_table"><tbody><tr><td class="pop_tl"></td><td class="pop_tc"></td><td class="pop_tr"></td></tr><tr><td class="pop_content" colspan="3"><div class="dialog_header"><div id="ui_dialog_header" class="dialog_title"></div><a id="ui_dialog_close" class="dialog_close" href="javascript:;" >\u5173\u95ed</a></div><div id="ui_dialog_body" class="dialog_body"></div><div id="ui_dialog_footer" class="dialog_footer"></div></td></tr><tr><td class="pop_bl"></td><td class="pop_bc"></td><td class="pop_br"></td></tr></tbody></table>'},
setOffsetX:function(b){a(this.frame).css("left",parseInt(a(this.frame).css("left"))+b)},setOffsetY:function(b){a(this.frame).css("top",parseInt(a(this.frame).css("top"))+b)},setWidth:function(b){a(this.frame).css("width",b);this.show();return this},setHeight:function(b){a(this.frame).css("height",b);this.show();return this},resizeTo:function(b,d){this.setWidth(b);this.setHeight(d);return this},addStyle:function(b){a(this.dialogContainer).addClass(b);return this},show:function(){var b=this;a(this.frame).hide();
var d,f;d=this.options.left||Math.max(parseInt((a.func.winWidth()-a(this.frame).width())/2),0)+a(document).scrollLeft();f=this.options.top||Math.max(parseInt((a.func.winHeight()-a(this.frame).height())/2),0)+a(document).scrollTop();d+=this.options.offsetX;f+=this.options.offsetY;this.moveTo(d,f);this.options.overlay&&a.DOM.disable();this.options.lock&&a.DOM.disable(true);this.options.fade&&!a.browser.msie?setTimeout(function(){a(b.frame).fadeIn(500)},0):setTimeout(function(){a(b.frame).show()},0);
if(this.options.clickClose){a(document).bind("click",b._clickClose);a(this.frame).click(function(h){h.stopPropagation()})}this.options.scrollCenter&&a(window).bind("scroll",b._scrollCenter);a(window).resize(function(){b.refresh()});return this},hide:function(){var b=this;if(this.options.fade&&!a.browser.msie)a(this.frame).fadeOut(function(){a(b.frame).css({left:-9999,top:-9999});a.DOM.enable()});else{a(this.frame).hide();a.DOM.enable()}a(document).unbind("click",b._clickClose);a(window).unbind("scroll",
b._scrollCenter);this.options.onHide();return this},remove:function(){a(document).unbind("keyup",this._addHotKey);a(this.frame).remove();a.DOM.enable();a(document).unbind("click",this._clickClose);return this},moveTo:function(b,d){a.func.isNumber(b)&&a(this.frame).css("left",b);a.func.isNumber(d)&&a(this.frame).css("top",d);return this},refresh:function(){var b,d;b=this.options.left||Math.max(parseInt((a.func.winWidth()-a(this.frame).width())/2),0)+a(document).scrollLeft();d=this.options.top||Math.max(parseInt((a.func.winHeight()-
a(this.frame).height())/2),0)+a(document).scrollTop();b+=this.options.offsetX;d+=this.options.offsetY;this.moveTo(b,d)},setX:function(b){moveTo(b);return this},setY:function(b){moveTo(null,b);return this},setIndex:function(b){a(this.frame).css("z-index",b);return this},setHeader:function(b){this.header.append(b);return this},setBody:function(b){this.body.append(b);return this},setFooter:function(b){this.footer.append(b);return this},addButton:function(b){var d=a("<input>").attr("type","button").attr("class",
"input-btn").addClass(b.className).val(b.text).click(function(){b.onclick()});this.footer.append(d);this._buttons.push(d);return this},getButton:function(b){for(var d=this._buttons,f=d.length-1;f>=0;f--)if(a(d[f]).val()==b)return d[f];return null},delButton:function(b){a(this.getButton(b)).remove();return this}};var e=null;a.alert=function(b){e&&e.remove();var d={};d=a.func.isString(b)?a.extend(d,{message:b}):a.extend(d,b);d=a.extend(d,{fade:false,clickClose:false});var f=(new a.dialog(d)).setHeader(d.title?
d.title:"\u63d0\u793a").setBody(d.message).addButton({text:d.yes?d.yes:"\u786e\u5b9a",onclick:function(){f.hide()},className:"btn-b-s-2"}).show();setTimeout(function(){f.getButton("\u786e\u5b9a").focus()},0);return e=f};var g=null;a.confirm=function(b,d){g&&g.remove();var f={};f=a.func.isString(b)?a.extend(f,{message:b,callback:d}):a.extend(f,b);f=a.extend(f,{fade:false,clickClose:false});var h=(new a.dialog(f)).setHeader(f.title?f.title:"\u63d0\u793a").setBody(f.message).addButton({text:f.yes?f.yes:
"\u786e\u5b9a",onclick:function(){f.callback&&f.callback(true);h.hide()},className:"btn-b-s-2"}).addButton({text:f.no?f.no:"\u53d6\u6d88",onclick:function(){f.callback&&f.callback(false);h.hide()},className:"btn-g-s-2"}).show();setTimeout(function(){h.getButton("\u786e\u5b9a").focus()},0);return g=h}})(jQuery);
function connectToRR(){var a="";if($("#buydata4reg")[0])a="?buydata="+buyDate2Str($("#dealBuyForm").serializeArray())+"&origURL="+$("#origURLLogin").val();else if($.trim(window.location.search)!="")a=window.location.search;setTimeout(function(){$.getScript("http://static.connect.renren.com/js/v1.0/FeatureLoader.jsp",function(){XN_RequireFeatures(["Connect"],function(){XN.Main.init("ca682808888647fbb86f1bf4b1331b9d","/xd_receiver.html");XN.Connect.requireSession(function(){setTimeout(function(){window.location.href=
"/user/renren"+a},10)})})})},50)}
function follow139(){setTimeout(function(){$.getScript("http://auth.139.com/connect/featureloader.php",function(){var a=setInterval(function(){if(MI&&MI.init){clearInterval(a);MI.init("9998a1b5f11eff0f24c249b9c1308070","http://www.nuomi.com/139proxy.htm");MI.Connect.requireSession(function(c){c.status==MI.ConnectState.connected&&$.post("/user/follow139",{u:c.userid,t:c.token},function(e){e.code==0&&$.alert({title:"<h3>\u7cef\u7c73\u63d0\u793a</h3>",message:'<p style="text-align:center; font-size:14px;"><span style="background:url(http://static.nuomi.com/img/icon/smile.png?v=20100629) no-repeat left center; display:inline-block; padding:25px 0 25px 35px; ">\u5173\u6ce8\u6210\u529f!</span></p>',overlay:true,
closeButton:true})},"json")},function(){})}},500)})},0)}
jQuery(function(){var a=null;window.showPopLogin=function(){if($("#loginForm")[0]&&!$("#loginRegDiv")[0])$("#emailLogin").focus();else{if(a)a.show();else{a=(new $.dialog({overlay:true,closeButton:true})).setHeader('<div class="login-title"><h3>\u767b\u5f55</h3><span>\u6216\u8005<a href="/reg">\u6ce8\u518c</a></span></div>').setBody('<div class="pop-login">\t<div class="login-form">\t\t<form id="loginFormPop" action="/login" method="post" name="login">\t\t\t<div class="field email">\t\t\t\t<label for="emailLoginPop">Email\uff1a</label>\t\t\t\t<div class="input-area">\t\t\t\t\t<p><input type="text" class="input-txt" id="emailLoginPop" name="email" tabindex="1" /></p>\t\t\t\t\t<p class="tip"></p>\t\t\t\t</div>\t\t\t\t<span class="msg" id="msgEmailLoginPop"></span>\t\t\t</div>\t\t\t<div class="field pass">\t\t\t\t<label for="passwordLoginPop">\u5bc6\u7801\uff1a</label>\t\t\t\t<div class="input-area">\t\t\t\t\t<p><input type="password" class="input-txt" id="passwordLoginPop" name="password" tabindex="2" /></p>\t\t\t\t\t<p class="tip"></p>\t\t\t\t</div>\t\t\t\t<span class="msg" id="msgPassLoginPop"></span>\t\t\t</div>\t\t\t<div class="field remember">\t\t\t\t<label for="remember"><input type="checkbox" name="remember" id="remember"  tabindex="3" />\u4e0b\u6b21\u81ea\u52a8\u767b\u5f55</label>\t\t\t\t<p><a href="/user/passwordRetrieve" tabindex="6">\u627e\u56de\u5bc6\u7801</a></p>\t\t\t</div>\t\t\t<div class="login-btn">\t\t\t\t<input type="hidden" value="'+window.location.pathname+
window.location.search+'" name="origURL" />\t\t\t\t<input type="submit" class="input-btn" value="\u767b\u5f55"  tabindex="4" />\t\t\t</div>\t\t</form>\t</div>\t<div class="connect2rr"><a href="javascript:;" id="connectRR"><img src="http://static.nuomi.com/img/connect-rr.png"  tabindex="5" /></a></div></div>').setFooter("").show();$("#connectRR").click(function(){connectToRR();a.hide()})}$("#emailLoginPop").bind("blur",function(){});$("#passwordLoginPop").bind("blur",function(){});$("#loginFormPop").bind("submit",
function(){});$("#loginFormPop .input-txt").each(function(){$(this).bind("focus",function(){$(this).addClass("focus")});$(this).bind("blur",function(){$(this).removeClass("focus")})});$("#emailLoginPop").focus()}};$("#showPopLoginLink")[0]&&$("#showPopLoginLink").click(function(c){c.stopPropagation()})});
function CountDown(a){if(a.startTime==null)throw"args:startTime is null";if(a.endTime==null)throw"args:endTime is null";this.startTime=a.startTime.constructor==Date?a.startTime.getTime():a.startTime;this.endTime=a.endTime.constructor==Date?a.endTime.getTime():a.endTime;this.callback=a.callback||new Function;this.startCount()}
CountDown.prototype={startCount:function(){var a=this.startTime,c=this.endTime,e=this.callback,g=setInterval(function(){a+=1E3;if(a>c)clearInterval(g);else{var b=(c-a)/1E3,d=parseInt(b/3600/24),f=parseInt((b-d*24*3600)/3600),h=parseInt((b-d*24*3600-f*3600)/60);b=parseInt(b-d*24*3600-f*3600-h*60);e(d,f,h,b)}},1E3)}};jQuery(function(){$("#menuMine")[0]&&$("#menuMine").mouseover(function(){$(this).addClass("hover")}).mouseout(function(){$(this).removeClass("hover")})});
jQuery(function(){$(".self-table")[0]&&$(".self-table tr").each(function(){$(this).mouseover(function(){$(this).addClass("hover")}).mouseout(function(){$(this).removeClass("hover")})})});jQuery(function(){$(".feed-btn")[0]&&$(".feed-btn").each(function(){$(this).mouseover(function(){$(this).addClass("feed-hover")}).click(function(){$(this).addClass("feed-activity")}).mouseout(function(){$(this).removeClass("feed-hover").removeClass("feed-activity")})})});
function copyCode(a){var c=$("#"+a).val();copy2Clipboard(c)!=false?$.alert('<p style="algin:center; padding:25px 0;">\u590d\u5236\u6210\u529f !</p>'):alert("\u60a8\u4f7f\u7528\u7684\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u6b64\u590d\u5236\u529f\u80fd\uff0c\u8bf7\u4f7f\u7528Ctrl+C\u6216\u9f20\u6807\u53f3\u952e\u3002");$("#"+a).focus().select()}copy2Clipboard=function(a){if(window.clipboardData){window.clipboardData.clearData();window.clipboardData.setData("Text",a);return true}else return false};
jQuery(function(){$("#dealBuyForm").submit(function(){if($("#confirmButton").attr("type")=="button"){$("#confirmButton").click();return false}if($("#addrName")[0]){var a=true;$("#dealBuyForm .addr-detail em").remove();if($.func.isBlank($("#addrName").val())){$("#addrName").after("<em>\u8bf7\u586b\u5199\u59d3\u540d</em>");a=false}if($.func.isBlank($("#addrAddr").val())){$("#addrAddr").after("<em>\u8bf7\u586b\u5199\u5730\u5740</em>");a=false}if($.func.isBlank($("#addrPhone").val())){$("#addrPhone").after("<em>\u8bf7\u586b\u5199\u7535\u8bdd</em>");
a=false}return a}})});jQuery(function(){$("#changeCity").click(function(a){$("#allCity").slideDown(300);a.stopPropagation();$(this).blur()});$("#allCity").click(function(a){a.stopPropagation()});$(document).click(function(a){a.button!=2&&$("#allCity").slideUp(300)});$("#foldin").click(function(){$("#allCity").slideUp(300)})});
jQuery(function(){$.emailSubscriber=function(a,c){this.form=$("#"+a);this.defaultValue=c||"\u8f93\u5165Email\u5730\u5740";this.errorMsg={emailBlank:"\u8bf7\u8f93\u5165\u60a8\u7684Email\u5730\u5740\u3002",emailError:"\u9519\u8bef\u7684\u7535\u5b50\u90ae\u4ef6\u5730\u5740\u54e6\uff01",cityBlank:"\u8bf7\u586b\u5199\u60a8\u7684\u57ce\u5e02"};this.ipt=$("#"+a+' input[name="email"]');this.emailAddress={"163.com":"163","126.com":"163","gmail.com":"gmail","qq.com":"qq","vip.qq.com":"qq","foxmail.com":"qq",
"live.com":"live","live.cn":"live","hotmail.com":"live","yahoo.com.cn":"yahoo","yahoo.cn":"yahoo","sina.com":"sina","vip.sina.com":"sina","sohu.com":"sohu","139.com":"139"};this.init()};$.emailSubscriber.prototype={init:function(){var a=this;this.setDefaultValue();this.form.submit(function(){a.post();return false})},setDefaultValue:function(){var a=this;this.ipt.val(this.defaultValue);this.ipt.focus(function(){if($(this).val()==a.defaultValue){$(this).val("");$(this).css("color","#333").css("font-weight",
"bold")}}).blur(function(){if($(this).val()==""){$(this).val(a.defaultValue);$(this).css("color","").css("font-weight","")}})},post:function(){var a=this;if(this.check()){var c=this.emailAddress[this.ipt.val().split("@")[1]],e=this.form.serialize();$.post("/subscribe/add",e,function(g){g.code==0?$.alert({title:"\u8ba2\u9605\u6210\u529f",message:'<div class="subs-alert">\t<div class="subs-succ"><h3>\u90ae\u4ef6\u8ba2\u9605\u6210\u529f\uff01</h3><p>\u6bcf\u5929\u7684\u56e2\u8d2d\u5c06\u53ca\u65f6\u53d1\u5230\u4f60\u90ae\u7bb1</p></div>\t<div class="subs-tip">\t\t<p>\u4f60\u53ef\u80fd\u6536\u4e0d\u5230\u8ba2\u9605\u90ae\u4ef6...</p>\t\t<p>\u8bf7\u5c06info@nuomi.com \u52a0\u5165\u90ae\u7bb1\u767d\u540d\u5355</p>\t\t<p><strong><a href="/help/email/'+
(c?c:"other")+'" target="_blank">\u7acb\u5373\u8fdb\u884c\u8bbe\u7f6e&raquo;</a></strong></p>\t</div></div>',overlay:true,closeButton:true,onHide:function(){a.ipt.focus()}}).footer.empty():$.alert({title:"<h3>\u7cef\u7c73\u63d0\u793a</h3>",message:'<p style="text-align:center; font-size:14px;"><span style="background:url(http://static.nuomi.com/img/icon/smile.png?v=20100629) no-repeat left center; display:inline-block; padding:25px 0 25px 35px; ">'+g.msg+"</span></p>",overlay:true,closeButton:true,
onHide:function(){a.ipt.focus()}})},"json")}},check:function(){var a=this;if($.func.isBlank(a.ipt.val())||a.ipt.val()==a.defaultValue){$.alert({title:"<h3>\u7cef\u7c73\u63d0\u793a</h3>",message:'<p style="text-align:center; font-size:14px;"><span style="background:url(http://static.nuomi.com/img/icon/smile.png?v=20100629) no-repeat left center; display:inline-block; padding:25px 0 25px 35px; ">'+a.errorMsg.emailBlank+"</span></p>",overlay:true,closeButton:true,onHide:function(){a.ipt.focus()}});return false}else if($.func.isEmail(a.ipt.val()))if($("#city:visible")[0]&&
$.trim($("#city:visible").val())==""){$.alert({title:"<h3>\u7cef\u7c73\u63d0\u793a</h3>",message:'<p style="text-align:center; font-size:14px;"><span style="background:url(http://static.nuomi.com/img/icon/smile.png?v=20100629) no-repeat left center; display:inline-block; padding:25px 0 25px 35px; ">'+a.errorMsg.cityBlank+"</span></p>",overlay:true,closeButton:true,onHide:function(){a.ipt.focus()}});return false}else return true;else{$.alert({title:"<h3>\u7cef\u7c73\u63d0\u793a</h3>",message:'<p style="text-align:center; font-size:14px;"><span style="background:url(http://static.nuomi.com/img/icon/fail.png?v=20100629) no-repeat left center; display:inline-block; padding:25px 0 25px 35px; ">'+
a.errorMsg.emailError+"</span></p>",overlay:true,closeButton:true,onHide:function(){a.ipt.focus()}});return false}}}});
jQuery.cookie=function(a,c,e){if(typeof c!="undefined"){e=e||{};if(c===null){c="";e.expires=-1}var g="";if(e.expires&&(typeof e.expires=="number"||e.expires.toUTCString)){if(typeof e.expires=="number"){g=new Date;g.setTime(g.getTime()+e.expires*24*60*60*1E3)}else g=e.expires;g="; expires="+g.toUTCString()}var b=e.path?"; path="+e.path:"",d=e.domain?"; domain="+e.domain:"";e=e.secure?"; secure":"";document.cookie=[a,"=",encodeURIComponent(c),g,b,d,e].join("")}else{c=null;if(document.cookie&&document.cookie!=
""){e=document.cookie.split(";");for(g=0;g<e.length;g++){b=jQuery.trim(e[g]);if(b.substring(0,a.length+1)==a+"="){c=decodeURIComponent(b.substring(a.length+1));break}}}return c}};
function openChat(a,c){if(c=="online")window.open(a,"chatWindow","width=500,height=520,toolbar=no,scrollbars=no,menubar=no,location=no,left="+Math.max((screen.width-500)/2,0)+",top="+Math.max((screen.height-600)/2,0));else window.location.href.indexOf("gossip")>=0?$.confirm({title:"\u5ba2\u670d\u5f53\u524d\u79bb\u7ebf",message:'<p style="text-align:center; padding:30px 0; font-size:14px;">\u975e\u5728\u7ebf\u5ba2\u670d\u5de5\u4f5c\u65f6\u95f4\uff0c\u5982\u6709\u95ee\u9898\u8bf7\u7ed9\u6211\u4eec\u7559\u8a00\uff0c\u6211\u4eec\u4f1a\u5c3d\u5feb\u56de\u590d\u3002</p>',width:440,
overlay:true,callback:function(e){if(e){window.location.hash="ask";$("#ask").show();$("#ask textarea").focus()}}}).getButton("\u53d6\u6d88").remove():$.confirm({title:"\u5f53\u524d\u5ba2\u670d\u4e0d\u5728\u7ebf",message:'<p style="text-align:center; padding:30px 0; font-size:14px;">\u975e\u5728\u7ebf\u5ba2\u670d\u5de5\u4f5c\u65f6\u95f4\uff0c\u5982\u6709\u95ee\u9898\u8bf7\u7ed9\u6211\u4eec\u7559\u8a00\uff0c\u6211\u4eec\u4f1a\u5c3d\u5feb\u56de\u590d\u3002</p>',width:440,overlay:true,callback:function(){}}).getButton("\u53d6\u6d88").remove()}
function showMsg(a){$.alert({message:'<p style="padding:20px 0; text-align:center; font-size:14px;">'+a+"</p>",overlay:true,closeButton:true})}
function sendToPhone(a){var c=a.sendNum.value;if($.func.isBlank(c)){showMsg("\u8bf7\u8f93\u5165\u624b\u673a\u53f7\uff01");return false}if(!$.func.isMobile(c)){showMsg("\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u624b\u673a\u53f7\uff01");return false}a=$(a).serialize();$.get("/user/certificateToSMS",a,function(e){if(e.code==0)showMsg("\u53d1\u9001\u6210\u529f");else if(e.code==1)showMsg("\u53d1\u9001\u77ed\u4fe1\u51fa\u4e86\u70b9\u5c0f\u6545\u969c\uff0c\u7a0d\u540e\u518d\u8bd5\u8bd5\u5427\uff01");else e.code==
2&&showMsg("\u6bcf\u5f20\u7cef\u7c73\u5238\u6bcf\u5929\u53ea\u80fd\u53d1\u4e09\u6b21\u54e6")},"json")}jQuery(function(){$.browser.msie&&$("label").click(function(){if($(this).children(":radio")[0].disabled!=true)if($(this).children(":radio")[0])$(this).children(":radio").attr("checked",true).blur();else $(this).attr("for")&&$(":radio#"+$(this).attr("for")).attr("checked",true).blur()})});
function buyDate2Str(a){var c=[];$.each(a,function(e,g){c.push('"'+g.name+'":"'+g.value+'"')});return c="{"+c.join(",")+"}"}function selectInput(a){$("#"+a).focus(function(){$(this).select()}).mousedown(function(c){c.preventDefault();$(this).select()})}jQuery(function(){setTimeout(function(){$(".error_msg,.success_msg").hide()},5E3)});
jQuery(function(){function a(){$("#want h3").addClass("activity");$("#wantWrap").slideDown(function(){e.val(b)})}if($("#want")[0]){var c=$("#curNum"),e=$("#wantForm textarea"),g=0,b="\u5728\u8fd9\u91cc\u5199\u4e0b\u4f60\u60f3\u56e2\u7684\u4e1c\u897f\u5427";$("#want h3").bind("click",a);c.text(g=$.trim(e.val()).length);e.keyup(function(){c.text(g=$.trim(e.val()).length);if(g>=140){e.val(e.val().substring(0,140)).attr("scrollTop",1E3);c.text(g=140).addClass("error")}else c.removeClass("error")}).focus(function(){$(this).addClass("focus");
$(this).val()==b&&$(this).val("")}).blur(function(){$(this).removeClass("focus");$(this).val()==""&&$(this).val(b)});a();$("#wantForm").submit(function(){g<=140&&g>0&&e.val()!=b&&$.post("/user/want",$("#wantForm").serialize(),function(d){if(d.code==0){$("#want h3").unbind("click",a);$("#wantWrap").hide();$("#want h3").removeClass("activity").addClass("success").text("\u53d1\u9001\u6210\u529f\uff01")}else alert(d.msg)},"json");return false})}});
jQuery(function(){if(!(typeof isStating=="undefined"||!isStating)){var a=$("#hd").offset().left;$(window).resize(function(){a=$("#hd").offset().left});$(document).mousedown(function(c){var e={};e.r=encodeURIComponent(window.location.href);c=c||window.event;var g,b,d=c.target||c.srcElement;if(d&&3==d.nodeType)d=d.parentNode;if(d&&d.tagName){b=d.tagName.toLowerCase();if(b=="img")g=d.src;else if(b=="a")g=d.href;if(g)e.u=encodeURIComponent(g);if(b)e.t=b;e.x=c.pageX-a;e.y=c.pageY;(new Image).src="http://click.nuomi.com/tj?"+
$.param(e)+"&s="+Math.random()}})}});
