using System;
using System.Collections.Generic;
using System.Text;
using System.Net;
using System.IO;
using System.Drawing;
using PowerTalkBoxContrls.Design;
using PowerTalkBoxEnum.Enum;

namespace PowerTalkBoxContrls.Design
{
   public class Html
   {
 
       public static  string WebClientGetSource(string url)
       {
           try
           {
               WebClient wc = new WebClient();
               Stream db = wc.OpenRead(url);
               StreamReader sr = new StreamReader(db, System.Text.Encoding.Default);
               string sc = sr.ReadToEnd();
               sr.Close();
               db.Close();
               wc.Dispose();
               return sc;
           }
           catch
           {             
               return"";
           }
       }
 
 public static string jsContent(int Interval)
 {
           string jsStr = "";

jsStr+="  <script>";
jsStr += "window.setInterval('ReadChatInfo();', " + Interval.ToString() + ");";
jsStr+="function ReadChatInfo()";
jsStr+="{";
jsStr+="GetArea('0&'+document.getElementById('MyUserId').innerHTML);";
jsStr+="}";
jsStr+="function SendFileInfo()";
jsStr+="{";
jsStr+="if(window.navigator.userAgent.indexOf(\"Firefox\")>=1)";
jsStr+="{";
jsStr+="IframeChatListBox.contentDocument.body.innerHTML+='<font color=red>文件发送中...</font><br/>';";
jsStr+="GetArea('2$'+document.getElementById('MyUserId').innerHTML+'$'+document.getElementById('ToUserID').innerHTML+'$'+document.getElementById('upfile').value);";
jsStr+="}";
jsStr+="else";
jsStr+="{";
jsStr+="IframeChatListBox.document.body.innerHTML+='<font color=red>文件发送中...</font><br/>';";
jsStr+="GetArea('2$'+document.getElementById('MyUserId').innerHTML+'$'+document.getElementById('ToUserID').innerHTML+'$'+document.getElementById('upfile').value);";
jsStr+="}";
jsStr+="}";
jsStr+="function SendInfo()";
jsStr+="{";
jsStr+=" if(window.navigator.userAgent.indexOf(\"Firefox\")>=1)";
jsStr+="{";
jsStr+="GetArea('1$'+document.getElementById('MyUserId').innerHTML+'$'+document.getElementById('ToUserID').innerHTML+'$'+IframeSendMsg.contentDocument.body.innerHTML);";
jsStr+="IframeSendMsg.contentDocument.body.innerHTML='';";
jsStr+="}";
jsStr+="else";
jsStr+="{";
jsStr+="GetArea('1$'+document.getElementById('MyUserId').innerHTML+'$'+document.getElementById('ToUserID').innerHTML+'$'+IframeSendMsg.document.body.innerHTML);";
jsStr+="IframeSendMsg.document.body.innerHTML='';";
jsStr+="}";
jsStr+="IframeSendMsg.focus();";
jsStr+="}";
jsStr+="function FormatText(command, option){";
jsStr+="IframeSendMsg.document.execCommand(command, true, option);";
jsStr+="IframeSendMsg.focus();";
jsStr+="}";
jsStr+="function changeSize(obj){ ";
jsStr+="FormatText('fontsize',obj.value);";
jsStr+="} ";
jsStr+="function changeFont(obj){ ";
jsStr+="FormatText('fontname' ,obj.value);";
jsStr+="} ";
jsStr+="function changeColors(obj){ ";
jsStr+="FormatText('ForeColor',obj.value);";
jsStr+="}";
jsStr+="function selImg(text){";
jsStr+="document.frames(\"SendMsg\").focus();";
jsStr+="var range =document.frames(\"SendMsg\").document.selection.createRange();";
jsStr+="var str1=\"<img src='\"+text+\"'/>\";";
jsStr+="range.pasteHTML(str1); ";
jsStr+="}";
jsStr+="function PowerTalk_showOrHide(value) {";
jsStr+="if(window.navigator.userAgent.indexOf(\"Firefox\")>=1)";
jsStr+="{";
jsStr+="alert('FireFox不支持本功能!');";
jsStr+="}";
jsStr+="else";
jsStr+="{";
jsStr+="    if (value==0) {";
jsStr+="        if (document.layers)";
jsStr+="           document.layers[\"Layer1\"].visibility='hide';";
jsStr+="        else";
jsStr+="           document.all[\"Layer1\"].style.visibility='hidden';";
jsStr+="   }";
jsStr+="   else if (value==1) {";
jsStr+="       if (document.layers)";
jsStr+="          document.layers[\"Layer1\"].visibility='show';";
jsStr+="       else";
jsStr+="          document.all[\"Layer1\"].style.visibility='visible';";
jsStr+="   }";
jsStr+="   }";
jsStr+="}";
jsStr+="function PowerTalk_showOrHide1(value) {";
jsStr+="if(window.navigator.userAgent.indexOf(\"Firefox\")>=1)";
jsStr+="{";
jsStr+="alert('FireFox不支持本功能!');";
jsStr+="}";
jsStr+="else";
jsStr+="{";
jsStr+="    if (value==0) {";
jsStr+="        if (document.layers)";
jsStr+="           document.layers[\"Layer2\"].visibility='hide';";
jsStr+="        else";
jsStr+="           document.all[\"Layer2\"].style.visibility='hidden';";
jsStr+="   }";
jsStr+="   else if (value==1) {";
jsStr+="       if (document.layers)";
jsStr+="          document.layers[\"Layer2\"].visibility='show';";
jsStr+="       else";
jsStr+="          document.all[\"Layer2\"].style.visibility='visible';";
jsStr+="   }";
jsStr+="   }";
jsStr+="}";
jsStr += "function PowerTalk_showOrHide2(value) {";
jsStr+="    if (value==0) {";
jsStr+="        if (document.layers)";
jsStr+="           document.layers[\"Layer3\"].visibility='hide';";
jsStr+="        else";
jsStr+="           document.all[\"Layer3\"].style.visibility='hidden';";
jsStr+="   }";
jsStr+="   else if (value==1) {";
jsStr+="       if (document.layers)";
jsStr+="          document.layers[\"Layer3\"].visibility='show';";
jsStr+="       else";
jsStr+="          document.all[\"Layer3\"].style.visibility='visible';";
jsStr+="   }";
jsStr+="}";
jsStr+="function PowerTalk_CmdSave()";
jsStr+="{";
jsStr+="if(window.navigator.userAgent.indexOf(\"Firefox\")>=1)";
jsStr+="{";
jsStr+="alert('FireFox不支持本功能!');";
jsStr+="}";
jsStr+="else";
jsStr+="{";
jsStr+="var OW = window.open('','','');";
jsStr+="var DD = new Date();";
jsStr+="OW.document.open();";
jsStr+="OW.document.write(IframeChatListBox.document.body.innerHTML);";
jsStr+="}";
jsStr+="OW.document.execCommand (\"SaveAs\",true,\"聊天记录-\"+ DD.getYear() + \"-\" + DD.getMonth() + \"-\" + DD.getDate() + \"-\" + DD.getHours() + \"-\" + DD.getMinutes() +\".htm\");";
jsStr+="OW.close();";
jsStr+="}";
jsStr+="function PowerTalk_Cls()";
jsStr+="{";
jsStr+="if(window.navigator.userAgent.indexOf(\"Firefox\")>=1)";
jsStr+="{";
jsStr+="IframeChatListBox.contentDocument.body.innerHTML='';";
jsStr+="}";
jsStr+="else";
jsStr+="{";
jsStr+="IframeChatListBox.document.body.innerHTML='';";
jsStr+="}";
jsStr+="}";
jsStr+="function set()";
jsStr+="{";
jsStr+="     if(window.navigator.userAgent.indexOf(\"Firefox\")>=1)";
jsStr+="    {";
jsStr+="    IframeSendMsg.contentDocument.body.innerHTML='123123';";
jsStr+="    IframeChatListBox.contentDocument.body.innerHTML='123123';";
jsStr+="    }";
jsStr+="    else";
jsStr+="    {";
jsStr+="    IframeSendMsg.document.body.innerHTML='321321';";
jsStr+="    IframeChatListBox.document.body.innerHTML='321321';";
jsStr+="    }";
jsStr+=" }";
jsStr+="var IframeChatListBox;";
jsStr+="var IframeSendMsg;";
jsStr+="function InitStart()";
jsStr+="{";
jsStr+="if(window.navigator.userAgent.indexOf(\"Firefox\")>=1)";
jsStr+="{";
jsStr+="IframeChatListBox=document.getElementById(\"ChatListBox\");";
jsStr+="IframeSendMsg = document.getElementById(\"SendMsg\");";
jsStr+="IframeSendMsg.contentWindow.document.designMode = \"On\";";
jsStr+="document.getElementById(\"KeyInput\").style.visibility='hidden';";
jsStr+="}";
jsStr+="else";
jsStr+="{";
jsStr+="IframeChatListBox=frames.document.frames(\"ChatListBox\");";
jsStr+="IframeSendMsg=frames.document.frames(\"SendMsg\");";
jsStr+="IframeSendMsg.document.designMode=\"on\";";
jsStr+="IframeSendMsg.document.onkeydown=new Function(\"return HotKeyPress(IframeSendMsg.event);\");";
jsStr+="}";
jsStr+="}";
jsStr+="function HotKeyPress(event)";
jsStr+="{	";
jsStr+="    var hotkey;";
jsStr+="    if(document.all.hotkey[0].checked) hotkey=0;";
jsStr+="    if(document.all.hotkey[1].checked) hotkey=1;";
jsStr+="    if(hotkey)";
jsStr+="    {";
jsStr+="        if(event.ctrlKey && event.keyCode==13)";
jsStr+="        {";
jsStr+="    SendInfo();";
jsStr+="        }";
jsStr+="    }";
jsStr+="    else";
jsStr+="    {";
jsStr+="        if(event.keyCode==13)";
jsStr+="        {";
jsStr+="    SendInfo();";
jsStr+="        }";
jsStr+="    }";
jsStr+="    if((event.ctrlKey && event.keyCode==67) || (event.altKey && event.keyCode==67))";
jsStr+="    {";
jsStr+="    confirm('请问您确定要离开PowerTalk?');";
jsStr+="    window.opener=null ;";
jsStr+="    window.close(); ";
jsStr+="    }";
jsStr += "}";


            return jsStr;
       
       }
 public static string TableContent()
       {
           string TableStr = "";
           TableStr = "<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">";
           TableStr += " <tr><td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">";
           TableStr += "  <tr>  <td width=\"136\" style=\"height: 49px\"><img src=\"images/PT_logo.gif\" alt=\"PowerTalk\" width=\"136\" height=\"49\" /></td>";
           TableStr += "    <td class=\"pt-headerbg\" style=\"height: 49px\"><img src=\"images/spacer.gif\" alt=\"space\" width=\"20\" height=\"1\" /></td>";
          TableStr += "  <td width=\"374\" class=\"pt-libname\" style=\"height: 49px\"><h2></h2></td>";
        TableStr += "  </tr></table></td> </tr>  <tr>";
        TableStr += " <td class=\"pt-fullbg\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">";
       TableStr += " <tr>          <td width=\"11\" class=\"pt-leftborder\" style=\"height: 368px\"><img src=\"images/PT_leftBorder.gif\" width=\"11\" height=\"5\" /></td>";
       TableStr += "   <td valign=\"top\" style=\"height: 368px; width: 100%;\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">";
        TableStr += "    <tr>     <td width=\"28\"><img src=\"images/border_ChatHead_left.gif\" width=\"28\" height=\"26\" /></td>";
         TableStr += "     <td class=\"pt-chatheader\">您正与 <strong><span id=\"ToUserID\" runat=\"server\"></span></strong> 交谈</td>";
         TableStr += "     <td style=\"width: 4px\"><img src=\"images/border_ChatHead_right.gif\" width=\"4\" height=\"26\" /></td>";
       TableStr += "     </tr>     </table>           <div class=\"pt-chatbox2\">              <label>";
       TableStr += "        <iframe src=\"ChatList.htm\" id=\"ChatListBox\"  width=\"100%\" height=\"218px\" ></iframe>       ";                  
         TableStr += "     </label>            </div>";
          TableStr += "  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"pt-iconbox\">";
         TableStr += "     <tr>                    <td width=\"6\"><img src=\"images/spacer.gif\" width=\"6\" height=\"1\" /></td>";
          TableStr += "      <td width=\"40px\" align=\"center\"><a href=\"#\" title=\"设置文本\"><img onClick=\"PowerTalk_showOrHide1(1),PowerTalk_showOrHide(0),PowerTalk_showOrHide2(0)\" src=\"images/Icon_txt.gif\" alt=\"设置文本\" width=\"16\" height=\"16\" border=\"0\" /></a></td>";
           TableStr += "     <td width=\"6px\"><img src=\"images/IconSpacer.gif\" width=\"6\" height=\"26\" /></td>";
           TableStr += "     <td width=\"40px\" align=\"center\"><a href=\"#\" title=\"增加表情\"><img onClick=\"PowerTalk_showOrHide(1),PowerTalk_showOrHide1(0),PowerTalk_showOrHide2(0)\" src=\"images/Icon_Face.gif\" alt=\"增加表情\" width=\"16\" height=\"16\" border=\"0\" /></a></td>";
           TableStr += "     <td width=\"6px\"><img src=\"images/IconSpacer.gif\" alt=\"\" width=\"6\" height=\"26\" /></td>";
           TableStr += "     <td width=\"40px\" align=\"center\"><a href=\"#\" title=\"传送文件\"><img onClick=\"PowerTalk_showOrHide2(1)\"  src=\"images/Icon_SendFile.gif\" alt=\"传送文件\" width=\"16\" height=\"16\" border=\"0\" /></a></td>";
            TableStr += "    <td width=\"6px\"><img src=\"images/IconSpacer.gif\" alt=\"\" width=\"6\" height=\"26\" /></td>";
            TableStr += "    <td width=\"40px\" align=\"center\"><a href=\"#\" title=\"保存通话记录\"><img onClick=\"PowerTalk_CmdSave()\" src=\"images/Icon_SaveData.gif\" alt=\"保存通话记录\" width=\"16\" height=\"16\" border=\"0\" /></a></td>";
             TableStr += "    <td width=\"6px\"><img src=\"images/IconSpacer.gif\" alt=\"\" width=\"6\" height=\"26\" /></td>";
             TableStr += "     <td width=\"40px\" align=\"center\"><a href=\"#\" title=\"清屏\"><img  onClick=\"PowerTalk_Cls();\" src=\"images/cas.gif\" alt=\"清屏\" width=\"16\" height=\"16\" /></a></td>";
             TableStr += "   <td  width=\"100%\"><div id=\"PowerTools\"></div></td>";
            TableStr += "  </tr>            </table>               <div class=\"pt-chatbox2\">              <label>";
           TableStr += "   <iframe src=\"blankpage.htm\" id=\"SendMsg\"  width=\"100%\" height=\"118px\" ></iframe>";
           TableStr += "   </label>            </div></td>";
        TableStr += "  <td width=\"6\" style=\"height: 368px\"><img src=\"images/spacer.gif\" alt=\"spacer2\" width=\"6\" height=\"1\" /></td>";
        TableStr += "  <td valign=\"top\" class=\"pt-controlbg\" style=\"height: 368px; width: 183px;\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">";
        TableStr += "    <tr>              <td width=\"24\" style=\"height: 26px\"><img src=\"images/border_AppraiseHead_Left.gif\" width=\"24\" height=\"26\" /></td>";
        TableStr += "      <td class=\"pt-rtbg\" style=\"height: 26px\"><strong><span id=\"MyUserId\" runat=\"server\">我的名称</span></strong></td>";
         TableStr += "     <td width=\"4\" style=\"height: 26px\"><img src=\"images/border_AppraiseHead_right.gif\" width=\"4\" height=\"26\" /></td>";
        TableStr += "    </tr>          </table>    ";
        TableStr += "  <div id=\"Engin_UserList\" runat=\"server\" class=\"pt-control\">";
         TableStr += "   <h3 style=\"height: 38px\">在线人数:<span id=\"OnlineCount\" runat=\"server\">0</span></h3>";
         TableStr += "   <p class=\"online\"><a href=\"#\" onclick=\"document.getElementById('ToUserID').innerHTML='1234'\" title=\"管理\">专家某某某1</a></p>";
          TableStr += "  <p class=\"leave\"><a href=\"#\">专家某某2</a></p>";
          TableStr += "  <p class=\"chatobject\"><a href=\"#\">专家某某某3</a></p>";
         TableStr += "   <p class=\"leave\"><a href=\"#\">专家某某某4</a></p>";
         TableStr += " </div>       ";
         TableStr += "     <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">";
         TableStr += "     <tr>              <td class=\"pt-appsend\" style=\"height: 25px\"><label>  ";           
          TableStr += "</table>          <img id=\"PowerTalkImg\" src=\"images/AD_NetInfo.jpg\" />   ";       
         TableStr += " </td>          <td class=\"pt-rightborder\" style=\"height: 368px; width: 11px;\"><img src=\"images/PT_rightBorder.gif\" width=\"11\" height=\"5\" /></td>";
        TableStr += "</tr>      </table></td>    </tr>    <tr>";
      TableStr += "<td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">";
       TableStr += " <tr>          <td width=\"11\" style=\"height: 50px\"><img src=\"images/PT_BottomLeft.gif\" width=\"11\" height=\"50\" /></td>";
        TableStr += "  <td class=\"pt-bottom\" style=\"height: 50px\">            <p id=\"KeyInput\">";
           TableStr += "     <input type=\"radio\"  name=\"hotkey\"  id=\"hotkey1\" value=\"0\">按 Enter 键发送";
				TableStr += "	<input  name=\"hotkey\" id=\"hotkey2\" type=\"radio\"  value=\"1\" checked>按 Ctrl+Enter 发送</p>";              
          TableStr += "  <label><input type=\"button\" name=\"Submit\" id=\"Submit\" value=\"发 送\" onclick=\"SendInfo()\" class=\"sendon\" onmouseover=\"this.className='sendover';\" onmouseout=\"this.className='sendon';\" />";
           TableStr += "   </label></td>";
         TableStr += " <td width=\"190\" class=\"pt-bombg\" style=\"height: 50px\"><img src=\"images/spacer.gif\" width=\"1\" height=\"1\" /></td>";
         TableStr += " <td width=\"11\" style=\"height: 50px\"><img src=\"images/PT_BottomRight.gif\" width=\"11\" height=\"50\" /></td>";
       TableStr += " </tr>      </table></td>    </tr>  </table>  ";
      // TableStr += "<script>InitStart();</script>";


           return TableStr;
       }
 public static string DivsContent()
       {
           string Dives = "";

           Dives += "        <div id=\"Layer2\" style=\"z-index: 1; left: 16px; visibility: hidden; width: 205px;";
           Dives += "    position: absolute; top: 245px; height: 20px; background-color: #ecf5ff; layer-background-color: #ECF5FF\">";
           Dives += "    <table border=\"1\" bordercolor=\"#cee7ff\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">";
           Dives += "        <tr>";
           Dives += "            <td width=\"20%\" height= 20px>";
           Dives += "                <select id=\"select1\"  name=\"select1\" onchange=\"changeFont(this);\">";
           Dives += "                    <option selected=\"selected\" value=\"宋体\">字体</option>";
           Dives += "                    <option value=\"宋体\">宋体</option>";
           Dives += "                    <option value=\"黑体\">黑体</option>";
           Dives += "                    <option value=\"幼圆\">幼圆</option>";
           Dives += "                    <option value=\"楷体\">楷体</option>";
           Dives += "                    <option value=\"隶书\">隶书</option>";
           Dives += "                    <option value=\"仿宋\">仿宋</option>";
           Dives += "                    <option value=\"华文彩云\">彩云</option>";
           Dives += "                    <option value=\"华文新魏\">新魏</option>";
           Dives += "                    <option value=\"华文行楷\">行楷</option>";
           Dives += "                </select>";
           Dives += "            </td>";
           Dives += "            <td width=\"20%\"  height= 20px>";
           Dives += "                <select id=\"select2\"  name=\"select2\" onchange=\"changeSize(this);\">";
           Dives += "                    <option selected=\"selected\" value=\"12\">字号</option>";
           Dives += "                    <option value=\"10\">10</option>";
           Dives += "                    <option value=\"12\">12</option>";
           Dives += "                    <option value=\"14\">14</option>";
           Dives += "                    <option value=\"16\">16</option>";
           Dives += "                    <option value=\"18\">18</option>";
           Dives += "                    <option value=\"20\">20</option>";
           Dives += "                    <option value=\"24\">24</option>";
           Dives += "                    <option value=\"36\">36</option>";
           Dives += "                </select>";
           Dives += "            </td>";
           Dives += "            <td width=\"20%\"  height= 20px>";
           Dives += "                <select id=\"select3\"  name=\"select3\" onchange=\"changeColors(this);\">";
           Dives += "                    <option selected=\"selected\">颜色</option>";
           Dives += "                    <option style=\"background-color: #000000\" value=\"#000000\">黑色</option>";
           Dives += "                    <option style=\"background-color: #888888\" value=\"#888888\">灰色</option>";
           Dives += "                    <option style=\"background-color: #ff0000\" value=\"#ff0000\">红色</option>";
           Dives += "                    <option style=\"background-color: #cc3366\" value=\"#cc3366\">暗红</option>";
           Dives += "                    <option style=\"background-color: #ff00ff\" value=\"#ff00ff\">紫红</option>";
           Dives += "                    <option style=\"background-color: #ee9966\" value=\"#ee9966\">橘黄</option>";
           Dives += "                    <option style=\"background-color: #aa00cc\" value=\"#aa00cc\">紫色</option>";
           Dives += "                    <option style=\"background-color: #8800ff\" value=\"#8800ff\">蓝紫</option>";
           Dives += "                    <option style=\"background-color: #ffff00\" value=\"#ffff00\">黄色</option>";
           Dives += "                    <option style=\"background-color: #ccaa00\" value=\"#ccaa00\">土黄</option>";
           Dives += "                    <option style=\"background-color: #ff8800\" value=\"#ff8800\">金黄</option>";
           Dives += "                    <option style=\"background-color: #0000ff\" value=\"#0000ff\">蓝色</option>";
           Dives += "                    <option style=\"background-color: #6699ee\" value=\"#6699ee\">天蓝</option>";
           Dives += "                    <option style=\"background-color: #0088ff\" value=\"#0088ff\">海蓝</option>";
           Dives += "                    <option style=\"background-color: #000088\" value=\"#000088\">深蓝</option>";
           Dives += "                    <option style=\"background-color: #00ff00\" value=\"#00ff00\">绿色</option>";
           Dives += "                    <option style=\"background-color: #888800\" value=\"#888800\">黄绿</option>";
           Dives += "                    <option style=\"background-color: #008888\" value=\"#008888\">蓝绿</option>";
           Dives += "                </select></td>";
           Dives += "                <td width=\"20%\"  height= 20px>";
           Dives += "                <input name=\"Submit2\" onclick=\"PowerTalk_showOrHide1(0),PowerTalk_showOrHide2(0),PowerTalk_showOrHide(0)\" type=\"button\" value=\"关闭\" />";
           Dives += "            </td>";
           Dives += "        </tr>";
           Dives += "    </table>";
           Dives += "</div>";
           Dives += "<div id=\"Layer1\" style=\"z-index: 1; left: 14px; visibility: hidden; width: 335px;";
           Dives += "    position: absolute; top: 180px; height: 38px; background-color: #ecf5ff\">";
           Dives += "    <table border=\"1\" bordercolor=\"#c8e3ff\" cellpadding=\"0\" cellspacing=\"0\" width=\"1%\">";
           Dives += "        <tr>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img1\" onclick=\"selImg(img1.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img1.gif\"";
           Dives += "                    title=\"大笑\" value=\"face/img1.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img2\" onclick=\"selImg(img2.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img2.gif\"";
           Dives += "                    title=\"色\" value=\"face/img2.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img3\" onclick=\"selImg(img3.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img3.gif\"";
           Dives += "                    title=\"生气\" value=\"face/img3.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img4\" onclick=\"selImg(img4.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img4.gif\"";
           Dives += "                    title=\"脸红\" value=\"face/img4.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img5\" onclick=\"selImg(img5.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img5.gif\"";
           Dives += "                    title=\"酷\" value=\"face/img5.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img6\" onclick=\"selImg(img6.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img6.gif\"";
           Dives += "                    title=\"晕\" value=\"face/img6.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img7\" onclick=\"selImg(img7.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img7.gif\"";
           Dives += "                    title=\"OhYes\" value=\"face/img7.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img8\" onclick=\"selImg(img8.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img8.gif\"";
           Dives += "                    title=\"嘘\" value=\"face/img8.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img9\" onclick=\"selImg(img9.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img9.gif\"";
           Dives += "                    title=\"哦?\" value=\"face/img9.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img10\" onclick=\"selImg(img10.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img10.gif\"";
           Dives += "                    title=\"干杯\" value=\"face/img10.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img11\" onclick=\"selImg(img11.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img11.gif\"";
           Dives += "                    title=\"酸\" value=\"face/img11.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img12\" onclick=\"selImg(img12.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img12.gif\"";
           Dives += "                    title=\"不要\" value=\"face/img12.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img13\" onclick=\"selImg(img13.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img13.gif\"";
           Dives += "                    title=\"骂\" value=\"face/img13.gif\" /></td>";
           Dives += "            <td style=\"height: 21px\">";
           Dives += "                <img id=\"img14\" onclick=\"selImg(img14.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img14.gif\"";
           Dives += "                    title=\"恶心\" value=\"face/img14.gif\" /></td>";
           Dives += "            <td style=\"height: 21px; width: 22px;\">";
           Dives += "                <img id=\"img15\" onclick=\"selImg(img15.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img15.gif\"";
           Dives += "                    title=\"闭嘴\" value=\"face/img15.gif\" /></td>";
           Dives += "        </tr>";
           Dives += "        <tr>";
           Dives += "            <td>";
           Dives += "                <img id=\"img16\" onclick=\"selImg(img16.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img16.gif\"";
           Dives += "                    title=\"怒\" value=\"face/img16.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img17\" onclick=\"selImg(img17.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img17.gif\"";
           Dives += "                    title=\"高手\" value=\"face/img17.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img18\" onclick=\"selImg(img18.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img18.gif\"";
           Dives += "                    title=\"鄙视\" value=\"face/img18.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img19\" onclick=\"selImg(img19.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img19.gif\"";
           Dives += "                    title=\"心碎\" value=\"face/img19.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img20\" onclick=\"selImg(img20.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img20.gif\"";
           Dives += "                    title=\"爱\" value=\"face/img20.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img21\" onclick=\"selImg(img21.value)\" onmouseup=\"showOrHide(0)\" src=\"face/img21.gif\"";
           Dives += "                    title=\"吻\" value=\"face/img21.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img22\" onclick=\"selImg(img22.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img22.gif\"";
           Dives += "                    title=\"枯萎\" value=\"face/img22.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img23\" onclick=\"selImg(img23.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img23.gif\"";
           Dives += "                    title=\"鲜花\" value=\"face/img23.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img24\" onclick=\"selImg(img24.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img24.gif\"";
           Dives += "                    title=\"礼物\" value=\"face/img24.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img25\" onclick=\"selImg(img25.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img25.gif\"";
           Dives += "                    title=\"苹果\" value=\"face/img25.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img26\" onclick=\"selImg(img26.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img26.gif\"";
           Dives += "                    title=\"西瓜\" value=\"face/img26.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img27\" onclick=\"selImg(img27.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img27.gif\"";
           Dives += "                    title=\"茶\" value=\"face/img27.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img28\" onclick=\"selImg(img28.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img28.gif\"";
           Dives += "                    title=\"电话\" value=\"face/img28.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img29\" onclick=\"selImg(img29.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img29.gif\"";
           Dives += "                    title=\"星星\" value=\"face/img29.gif\" /></td>";
           Dives += "            <td style=\"width: 22px\">";
           Dives += "                <img id=\"img30\" onclick=\"selImg(img30.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img30.gif\"";
           Dives += "                    title=\"不乐意\" value=\"face/img30.gif\" /></td>";
           Dives += "        </tr>";
           Dives += "        <tr>";
           Dives += "            <td>";
           Dives += "                <img id=\"img31\" onclick=\"selImg(img31.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img31.gif\"";
           Dives += "                    title=\"开心\" value=\"face/img31.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img32\" onclick=\"selImg(img32.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img32.gif\"";
           Dives += "                    title=\"羞愧\" value=\"face/img32.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img33\" onclick=\"selImg(img33.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img33.gif\"";
           Dives += "                    title=\"财迷\" value=\"face/img33.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img34\" onclick=\"selImg(img34.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img34.gif\"";
           Dives += "                    title=\"可爱\" value=\"face/img34.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img35\" onclick=\"selImg(img35.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img35.gif\"";
           Dives += "                    title=\"猪\" value=\"face/img35.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img36\" onclick=\"selImg(img36.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img36.gif\"";
           Dives += "                    title=\"大便\" value=\"face/img36.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img37\" onclick=\"selImg(img37.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img37.gif\"";
           Dives += "                    title=\"月亮\" value=\"face/img37.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img38\" onclick=\"selImg(img38.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img38.gif\"";
           Dives += "                    title=\"音乐\" value=\"face/img38.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img39\" onclick=\"selImg(img39.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img39.gif\"";
           Dives += "                    title=\"下雨\" value=\"face/img39.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img40\" onclick=\"selImg(img40.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img40.gif\"";
           Dives += "                    title=\"老鼠\" value=\"face/img40.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img41\" onclick=\"selImg(img41.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img41.gif\"";
           Dives += "                    title=\"小狗\" value=\"face/img41.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img42\" onclick=\"selImg(img42.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img42.gif\"";
           Dives += "                    title=\"骷髅\" value=\"face/img42.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img43\" onclick=\"selImg(img43.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img43.gif\"";
           Dives += "                    title=\"监视\" value=\"face/img43.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img44\" onclick=\"selImg(img44.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img44.gif\"";
           Dives += "                    title=\"太阳\" value=\"face/img44.gif\" /></td>";
           Dives += "            <td style=\"width: 22px\">";
           Dives += "                <img id=\"img45\" onclick=\"selImg(img45.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img45.gif\"";
           Dives += "                    title=\"信件\" value=\"face/img45.gif\" /></td>";
           Dives += "        </tr>";
           Dives += "        <tr>";
           Dives += "            <td>";
           Dives += "                <img id=\"img46\" onclick=\"selImg(img46.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img46.gif\"";
           Dives += "                    title=\"飞眼\" value=\"face/img46.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img47\" onclick=\"selImg(img47.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img47.gif\"";
           Dives += "                    title=\"电视\" value=\"face/img47.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img48\" onclick=\"selImg(img48.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img48.gif\"";
           Dives += "                    title=\"钟表\" value=\"face/img48.gif\" /></td>";
           Dives += "            <td>";
           Dives += "                <img id=\"img49\" onclick=\"selImg(img49.value)\" onmouseup=\"PowerTalk_showOrHide(0)\" src=\"face/img49.gif\"";
           Dives += "                    title=\"灯泡\" value=\"face/img49.gif\" /></td>";
           Dives += "                    <td>";
           Dives += "                </td>";
           Dives += "        </tr>   ";
           Dives += "    </table>";
           Dives += "    <input name=\"closebutton\" onclick=\"PowerTalk_showOrHide1(0),PowerTalk_showOrHide2(0),PowerTalk_showOrHide(0)\" type=\"button\" value=\"关闭\" />";
           Dives += "</div>    ";
           Dives += "<span id=\"Layer3\" style=\"border-right: #000000 1px; border-top: #000000 1px; z-index: 1;";
           Dives += "    left: 14px; visibility: hidden; overflow: hidden; border-left: #000000 1px; width: 314px;";
           Dives += "    border-bottom: #000000 1px; position: absolute; top: 196px; height: 69px; background-color: #f7fbff;";
           Dives += "    layer-background-color: #F7FBFF\">";
           Dives += "    <div align=\"left\">";
           Dives += "        <table border=\"0\" style=\"width: 99%; height: 27px\">";
           Dives += "            <tr>";
           Dives += "                <td colspan=\"3\" style=\"width: 342px; height: 18px\">";
           Dives += "                    <div align=\"left\">";
           Dives += "                        <font color=\"#ff0000\" size=\"2\">限doc、rar、jpg、gif、png、bmp、swf、zip类型。</font></div>";
           Dives += "                </td>";
           Dives += "            </tr>";
           Dives += "            <tr>";
           Dives += "                <td style=\"width: 4%; height: 26px\">";
           Dives += "                    <font size=\"2\">";
           Dives += "                        <input id=\"upfile\" type=\"file\"  /> ";
           Dives += "                    </font>";
           Dives += "                </td>";
           Dives += "                <td style=\"width: 10%; height: 26px\">";
           Dives += "         <input id=\"SendFile\" type=\"button\" value=\"发送\" onclick=\"SendFileInfo();PowerTalk_showOrHide2(0)\" />";
           Dives += "              </td>";
           Dives += "              <td style=\"width: 13%; height: 26px\">";
           Dives += "              <input name=\"Submit2\" onclick=\"PowerTalk_showOrHide2(0)\" type=\"button\" value=\"关闭\" />";
           Dives += "                         </td>   ";
           Dives += "            </tr>";
           Dives += "        </table>";
           Dives += "    </div>";
           Dives += "</span>";

          return Dives;       
       }




   }
}
