(function(){
var g=false,i=null,l=true,aa=(new Date).getTime();var ba={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_gl:"gl",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_targeting:"targeting",google_ui_features:"ui",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type",google_page_url:"url"},ca={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_analytics_uacct:"ga_wpids",
google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"};function da(){}da.prototype.Hb=function(){};da.prototype.Ib=function(){};da.prototype.Gb=function(){};var n=i;function ea(a){n&&n.Hb(a)}function fa(a){n&&n.Ib(a)}function ga(a){n&&n.Gb(a)}function r(){this.I=this.wb();this.qa=g;if(!this.I){this.qa=this.bb();this.qa||fa("Browser does not allow cookies")}}r.prototype.ha="__gads=";r.prototype.R="GoogleAdServingTest=";r.prototype.ib=function(){return this.I};
r.prototype.setCookieInfo=function(a){this.C=a._cookies_[0];if(this.C!=i){this.I=this.C._value_;this.Fb()}};r.prototype.eb=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};
r.prototype.db=function(a){if(this.I!=i||!this.qa){ea("Skipping fetch cookie call");return}var b="script",c=document.domain,d="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo&client="+ha(a)+"&domain="+ha(c);ea("Issuing a fetch cookie call with <a href='"+d+"'>"+d+"</a>");document.write("<"+b+' src="'+d+'"></'+b+">")};
r.prototype.bb=function(){document.cookie=this.R+"Good";var a=this.Ea(this.R),b=a=="Good";if(b){var c=this.eb(-1);document.cookie=this.R+"; expires="+c.toGMTString()}return b};r.prototype.wb=function(){var a=this.Ea(this.ha);a!=i?ea("Read first party cookie: "+a):fa("No first party cookie found");return a};r.prototype.Ea=function(a){var b=document.cookie,c=b.indexOf(a),d=i;if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};
r.prototype.Fb=function(){if(this.C==i)fa("Skipping cookie creation: no cookie info");else if(this.I==i)ga("Skipping cookie creation: no cookie value");else{var a=new Date;a.setTime(1000*this.C._expires_);var b=this.C._domain_,c=this.ha+this.I+"; expires="+a.toGMTString()+"; path="+this.C._path_+"; domain=."+b;document.cookie=c;ea("Written cookie: "+c)}};function ia(a,b){var c;return a?(c=parseFloat(a))?c:b:b}
function ja(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var b=3,c=1;while(c)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=i}return b.toString()}else if(ka()){var c=i;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){var b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
b=6;c.AllowScriptAccess="always"}catch(d){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(c!=i){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"};var la=la||{},s=this;var na=function(a,b,c){var d=a.split("."),e=c||s,f;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);while(d.length&&(f=d.shift()))if(!d.length&&ma(b))e[f]=b;else e=e[f]?e[f]:(e[f]={})},oa=function(a,b){var c=a.split("."),d=b||s;for(var e;e=c.shift();)if(d[e])d=d[e];else return i;return d};
var t=function(a){var b=typeof a;if(b=="object")if(a){if(typeof a.length=="number"&&typeof a.splice!="undefined"&&!pa(a,"length"))return"array";if(typeof a.call!="undefined")return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},qa=function(a,b){if(b in a)for(var c in a)if(c==b&&Object.prototype.hasOwnProperty.call(a,b))return l;return g};
if(Object.prototype.propertyIsEnumerable)var pa=function(a,b){return a instanceof Object?Object.prototype.propertyIsEnumerable.call(a,b):qa(a,b)};else pa=qa;var ma=function(a){return typeof a!="undefined"};
var ra=function(a){var b=t(a);return b=="array"||b=="object"&&typeof a.length=="number"},sa=function(a){return typeof a=="string"},ta=function(a){return t(a)=="function"},ua=function(a){var b=t(a);return b=="object"||b=="array"||b=="function"},xa=function(a){if(a.hasOwnProperty&&a.hasOwnProperty(va)){var b=a[va];if(b)return b}a[va]||(a[va]=++wa);return a[va]},va="closure_hashCode_",wa=0,u=function(a,b){var c=a.Jb;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);c&&d.unshift.apply(d,
c);c=d}b=a.Lb||b;a=a.Kb||a;var e,f=b||s;e=c?function(){var h=Array.prototype.slice.call(arguments);h.unshift.apply(h,c);return a.apply(f,h)}:function(){return a.apply(f,arguments)};e.Jb=c;e.Lb=b;e.Kb=a;return e},ya=Date.now||function(){return(new Date).getTime()},za=function(a,b,c){na(a,b,c)},v=function(a,b){function c(){}c.prototype=b.prototype;a.p=b.prototype;a.prototype=new c;a.prototype.constructor=a};var Aa=function(a,b,c){if(a.indexOf)return a.indexOf(b,c);if(Array.indexOf)return Array.indexOf(a,b,c);var d=c==i?0:c<0?Math.max(0,a.length+c):c;for(var e=d;e<a.length;e++)if(e in a&&a[e]===b)return e;return-1},Ba=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else{var d=a.length,e=sa(a)?a.split(""):a;for(var f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)}},Ca=function(a,b){var c=Aa(a,b),d;if(d=c!=-1)Array.prototype.splice.call(a,c,1).length==1;return d};
var Da=function(a){if(t(a)=="array")return a.concat();else{var b=[];for(var c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var Ea=function(a,b){this.x=ma(a)?a:0;this.y=ma(b)?b:0};Ea.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var x=function(a,b){this.width=a;this.height=b};x.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};x.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};x.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};x.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
x.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Fa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var Ga=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ma=function(a,b){if(b)return a.replace(Ha,"&amp;").replace(Ia,"&lt;").replace(Ja,"&gt;").replace(Ka,"&quot;");else{if(!La.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(Ha,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(Ia,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(Ja,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(Ka,"&quot;");return a}},Ha=/&/g,Ia=/</g,Ja=/>/g,Ka=/\"/g,La=/[&<>\"]/,Na=function(a,b){var c=b.length;for(var d=0;d<c;d++){var e=
c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},Pa=function(a,b){var c=0,d=Ga(String(a)).split("."),e=Ga(String(b)).split("."),f=Math.max(d.length,e.length);for(var h=0;c==0&&h<f;h++){var j=d[h]||"",k=e[h]||"",m=new RegExp("(\\d*)(\\D*)","g"),o=new RegExp("(\\d*)(\\D*)","g");do{var p=m.exec(j)||["","",""],q=o.exec(k)||["","",""];if(p[0].length==0&&q[0].length==0)break;var w=p[1].length==0?0:parseInt(p[1],10),M=q[1].length==0?0:parseInt(q[1],
10);c=Oa(w,M)||Oa(p[2].length==0,q[2].length==0)||Oa(p[2],q[2])}while(c==0)}return c},Oa=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa,Ya,Za,$a,ab=function(){if(s.navigator)return s.navigator.userAgent;return i},bb=function(){var a=g,b=g,c=g,d=g,e=g,f=g,h=g,j=g,k=g,m="",o=ab();if(o){var p=s.navigator;a=o.indexOf("Opera")==0;b=!a&&o.indexOf("MSIE")!=-1;c=!a&&o.indexOf("WebKit")!=-1;k=c&&o.indexOf("Mobile")!=-1;d=!a&&!c&&p.product=="Gecko";e=d&&p.vendor=="Camino";var q,w;if(s.opera&&typeof s.opera.version=="function")q=s.opera.version();else{if(d)w=/rv\:([^\);]+)(\)|;)/;else if(b)w=/MSIE\s+([^\);]+)(\)|;)/;
else if(c)w=/WebKit\/(\S+)/;if(w){w.test(o);q=RegExp.$1}}m=p.platform||"";f=m.indexOf("Mac")!=-1;h=m.indexOf("Win")!=-1;j=m.indexOf("Linux")!=-1}Qa=a;Ra=b;Sa=d;Ta=e;Ua=c;Va=k;Wa=q;Xa=m;Ya=f;Za=h;$a=j};bb();var cb=Qa,y=Ra,db=Sa,z=Ua,ib=Va;var A=function(a){return Pa(Wa,a)>=0};var jb;var kb=function(){jb||(jb=new B);return jb},mb=function(a){return a?new B(lb(a)):kb()};
var nb=function(a){return sa(a)?document.getElementById(a):a},ob=nb,qb=function(a,b){Fa(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in pb)a.setAttribute(pb[d],c);else a[d]=c})},pb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder"},rb=function(a){var b=a||s||window,c=b.document;if(z&&!A("500")&&!ib){if(typeof b.innerHeight==
"undefined")b=window;var d=b.innerHeight,e=b.document.documentElement.scrollHeight;if(b==b.top)if(e<d)d-=15;return new x(b.innerWidth,d)}var f=mb(c),h=f.gb()=="CSS1Compat"&&(!cb||cb&&A("9.50"))?c.documentElement:c.body;return new x(h.clientWidth,h.clientHeight)};var sb=function(a,b){a.appendChild(b)},tb=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):i},ub=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};
var vb=z&&Pa(Wa,"521")<=0,wb=function(a,b){if(typeof a.contains!="undefined"&&!vb&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);while(b&&a!=b)b=b.parentNode;return b==a},lb=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},xb=function(a){if(a&&typeof a.length=="number")if(ua(a))return typeof a.item=="function"||typeof a.item=="string";else if(ta(a))return typeof a.item=="function";return g},
B=function(a){this.n=a||s.document||document};B.prototype.X=function(){return this.n};B.prototype.xa=function(a){return sa(a)?this.n.getElementById(a):a};B.prototype.Ua=function(a,b){if(y&&b&&b.name)a="<"+a+' name="'+Ma(b.name)+'">';var c=this.createElement(a);b&&qb(c,b);if(arguments.length>2){function d(h){if(h)this.appendChild(c,sa(h)?this.createTextNode(h):h)}for(var e=2;e<arguments.length;e++){var f=arguments[e];ra(f)&&!(ua(f)&&f.nodeType>0)?Ba(xb(f)?Da(f):f,d,this):d.call(this,f)}}return c};
B.prototype.createElement=function(a){return this.n.createElement(a)};B.prototype.createTextNode=function(a){return this.n.createTextNode(a)};B.prototype.gb=function(){if(this.n.compatMode)return this.n.compatMode;if(z){var a=this.Ua("div",{style:"position:absolute;width:0;height:0;width:1"}),b=a.style.width=="1px"?"BackCompat":"CSS1Compat";return this.n.compatMode=b}return"BackCompat"};
B.prototype.wa=function(){var a=this.n,b,c;if(!z&&a.compatMode=="CSS1Compat"){b=a.documentElement.scrollLeft;c=a.documentElement.scrollTop}else{b=a.body.scrollLeft;c=a.body.scrollTop}return new Ea(b,c)};B.prototype.appendChild=sb;B.prototype.removeNode=tb;B.prototype.replaceNode=ub;B.prototype.contains=wb;var yb,zb=function(a,b){var c=lb(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return i};
var Ab=function(a){return zb(a,"position")||(a.currentStyle?a.currentStyle.position:i)||a.style.position},Bb=function(a){var b;b=a?a.nodeType==9?a:lb(a):kb().X();if(y&&b.compatMode!="CSS1Compat")return b.body;return b.documentElement},Cb=function(a){var b=lb(a),c=db&&b.getBoxObjectFor&&Ab(a)=="absolute"&&(a.style.top==""||a.style.left=="");if(typeof yb=="undefined")yb=Ta&&!A("1.8.0.11");var d=new Ea(0,0),e=Bb(b);if(a==e)return d;var f=i,h;if(a.getBoundingClientRect&&!c){h=a.getBoundingClientRect();
var j=mb(b).wa();d.x=h.left+j.x;d.y=h.top+j.y}else if(b.getBoxObjectFor&&!c&&!yb){h=b.getBoxObjectFor(a);var k=b.getBoxObjectFor(e);d.x=h.screenX-k.screenX;d.y=h.screenY-k.screenY}else{f=a;do{d.x+=f.offsetLeft;d.y+=f.offsetTop;if(f!=a){d.x+=f.clientLeft||0;d.y+=f.clientTop||0}if(z&&Ab(f)=="fixed"){d.x+=b.body.scrollLeft;d.y+=b.body.scrollTop;break}f=f.offsetParent}while(f&&f!=a);if(cb||z&&Ab(a)=="absolute")d.y-=b.body.offsetTop;f=a.offsetParent;while(f&&f!=b.body){d.x-=f.scrollLeft;if(!cb||f.tagName!=
"TR")d.y-=f.scrollTop;f=f.offsetParent}}if(db&&a.getBoundingClientRect){var m=Ab(a);if(m=="static"||m=="relative"){d.x=Math.floor(d.x);d.y=Math.floor(d.y)}}return d},Db=function(a){var b=new Ea;if(a.nodeType==1)if(a.getBoundingClientRect){var c=a.getBoundingClientRect();b.x=c.left;b.y=c.top}else{var d=mb(a).wa(),e=Cb(a);b.x=e.x-d.x;b.y=e.y-d.y}else{b.x=a.clientX;b.y=a.clientY}return b},Eb=function(a){var b=lb(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=
zb(a,"fontFamily")||(a.currentStyle?a.currentStyle.fontFamily:i)||a.style.fontFamily;if(cb&&$a)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return Na(c,"\"'")};var Fb=document,C=navigator,D=window;
function Gb(){var a=Fb.cookie,b=Math.round((new Date).getTime()/1000),c=D.google_analytics_domain_name,d=typeof c=="undefined"?Hb("auto"):Hb(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,h=a.indexOf("__utmc="+d)>-1,j,k={};if(e){j=a.split("__utma="+d+".")[1].split(";")[0].split(".");k.sid=f&&h?j[3]+"":D&&D.gaGlobal&&D.gaGlobal.sid?D.gaGlobal.sid:b+"";k.vid=j[0]+"."+j[1];k.from_cookie=l}else{k.sid=D&&D.gaGlobal&&D.gaGlobal.sid?D.gaGlobal.sid:b+"";k.vid=D&&D.gaGlobal&&D.gaGlobal.vid?
D.gaGlobal.vid:(Ib()^Jb()&2147483647)+"."+b;k.from_cookie=g}k.dh=d;k.hid=D&&D.gaGlobal&&D.gaGlobal.hid?D.gaGlobal.hid:Ib();D.gaGlobal=k;return k}function Ib(){return Math.round(Math.random()*2147483647)}
function Jb(){var a=Fb.cookie?Fb.cookie:"",b=D.history.length,c,d,e=[C.appName,C.version,C.language?C.language:C.browserLanguage,C.platform,C.userAgent,C.javaEnabled()?1:0].join("");if(D.screen)e+=D.screen.width+"x"+D.screen.height+D.screen.colorDepth;else if(D.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=Fb.referrer?Fb.referrer:"";c=e.length;while(b>0)e+=b--^c++;return Kb(e)}
function Kb(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Hb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=Fb.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Kb(a.toLowerCase())};var E=function(){};E.prototype.va=g;E.prototype.dispose=function(){if(!this.va){this.b();this.va=l}};E.prototype.b=function(){};var Lb=function(a){if(/^\s*$/.test(a))return g;var b=/\\["\\\/bfnrtu]/g,c=/"[^"\\\n\r\u2028\u2029\x00-\x1f\x7f-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e=/^[\],:{}\s\u2028\u2029]*$/;return e.test(a.replace(b,"@").replace(c,"]").replace(d,""))},Mb=function(a){String(a);if(Lb(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Nb=i,Ob=function(a){Nb||(Nb=new F);return Nb.serialize(a)},F=function(){};
F.prototype.serialize=function(a){var b=[];this.fa(a,b);return b.join("")};F.prototype.fa=function(a,b){switch(typeof a){case "string":this.Ha(a,b);break;case "number":this.Cb(a,b);break;case "boolean":b.push(a);break;case "undefined":b.push("null");break;case "object":if(a==i){b.push("null");break}if(t(a)=="array"){this.Bb(a,b);break}this.Db(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};
var Pb={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"};F.prototype.Ha=function(a,b){b.push('"',a.replace(/[\\\"\x00-\x1f\x80-\uffff]/g,function(c){if(c in Pb)return Pb[c];var d=c.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return Pb[c]=e+d.toString(16)}),'"')};F.prototype.Cb=function(a,b){b.push(isFinite(a)&&!isNaN(a)?a:"null")};
F.prototype.Bb=function(a,b){var c=a.length;b.push("[");var d="";for(var e=0;e<c;e++){b.push(d);this.fa(a[e],b);d=","}b.push("]")};F.prototype.Db=function(a,b){b.push("{");var c="";for(var d in a)if(a.hasOwnProperty(d)){var e=a[d];if(typeof e!="function"){b.push(c);this.Ha(d,b);b.push(":");this.fa(e,b);c=","}}b.push("}")};var G="SETUP_ACK",H={},Rb=function(a,b){var c=b||Qb,d=c.length,e="";while(a-- >0)e+=c.charAt(Math.floor(Math.random()*d));return e},Qb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var I=function(){};v(I,E);I.prototype.f=0;var J=function(a){this.a=a;this.P=[];this.Qb=u(this.$a,this)};v(J,I);J.prototype.f=2;J.prototype.ba=g;J.prototype.Eb=0;J.prototype.connect=function(){if(this.a.s()==0){this.l=this.a.t;this.l.XPC_toOuter=u(this.ya,this)}else this.ma()};
J.prototype.ma=function(){var a=l;try{if(!this.l)this.l=window.frameElement;if(this.l&&this.l.XPC_toOuter){this.Ca=this.l.XPC_toOuter;this.l.XPC_toOuter.XPC_toInner=u(this.ya,this);a=g;this.send("tp",G);this.a.m()}}catch(b){}if(a){if(!this.Ma)this.Ma=u(this.ma,this);window.setTimeout(this.Ma,100)}};J.prototype.H=function(a){if(this.a.s()==0&&!this.a.g()&&a==G){this.Ca=this.l.XPC_toOuter.XPC_toInner;this.a.m()}else throw Error("Got unexpected transport message.");};
J.prototype.ya=function(a,b){if(!this.ba&&this.P.length==0)this.a.j(a,b);else{this.P.push({serviceName:a,payload:b});if(this.P.length==1)this.Eb=window.setTimeout(this.Qb,1)}};J.prototype.$a=function(){while(this.P.length){var a=this.P.shift();this.a.j(a.serviceName,a.payload)}};J.prototype.send=function(a,b){this.ba=l;this.Ca(a,b);this.ba=g};J.prototype.b=function(){J.p.b.call(this);this.Ca=i;this.l=i};var K=function(a){this.a=a;this.Q=this.a.c.ppu;this.Sb=this.a.c.lpu;this.da=[]},Sb,Tb;v(K,I);K.prototype.f=4;K.prototype.ea=0;K.prototype.w=g;K.prototype.Y=g;var Ub="googlexpc";K.prototype.M=function(){return Ub+"_"+this.a.name+"_msg"};K.prototype.L=function(){return Ub+"_"+this.a.name+"_ack"};K.prototype.connect=function(){if(!this.Y){this.Sa();this.Y=l}this.Oa()};K.prototype.Sa=function(){var a=this.M();this.D=this.U(a);this.Aa=window.frames[a];a=this.L();this.z=this.U(a);this.ia=window.frames[a]};
K.prototype.U=function(a){var b=kb().createElement("iframe"),c=b.style;c.position="absolute";c.top="-10px";c.left="10px";c.width="1px";c.height="1px";b.id=b.name=a;b.src=this.Q+"#INITIAL";document.body.appendChild(b);return b};K.prototype.la=function(){var a=this.a.h.frames,b=a.length;for(var c=0;c<b;c++){var d;try{if(a[c]&&a[c].name)d=a[c].name}catch(e){}if(!d)continue;var f=d.split("_");if(f.length==3&&f[0]==Ub&&f[1]=="reconnect"){this.a.name=f[2];this.Ya();this.Y=g;break}}};
K.prototype.Ya=function(){if(this.D){this.D.parentNode.removeChild(this.D);this.D=i;this.Aa=i}if(this.z){this.z.parentNode.removeChild(this.z);this.z=i;this.ia=i}};
K.prototype.Oa=function(){if(this.za(this.M())&&this.za(this.L())){this.pb=new Vb(this,this.a.h.frames[this.M()],u(this.ub,this));this.La=new Vb(this,this.a.h.frames[this.L()],u(this.tb,this));this.pa()}else{if(this.a.s()==1&&!this.Ub)this.Ub=this.U(Ub+"_reconnect_"+this.a.name);else this.a.s()==0&&this.la();window.setTimeout(u(this.connect,this),100)}};K.prototype.za=function(a){try{var b=this.a.h.frames[a];if(!b||b.location.href.indexOf(this.Sb)!=0)return g}catch(c){return g}return l};
K.prototype.pa=function(){var a=this.a.h.frames;if(a[this.L()]&&a[this.M()]){this.qb=new Wb(this.Q,this.Aa);this.S=new Wb(this.Q,this.ia);window.setTimeout(u(function(){this.qb.send("SETUP");this.Wb=l;this.w=l},this),100)}else{if(!this.Pa)this.Pa=u(this.pa,this);window.setTimeout(this.Pa,100)}};K.prototype.oa=function(){if(this.Ab&&this.Tb){this.a.m();if(this.K){for(var a=0,b;a<this.K.length;a++){b=this.K[a];this.a.j(b.service,b.payload)}delete this.K}}};
K.prototype.ub=function(a){if(a=="SETUP"){if(!this.S)return;this.S.send(G);this.Ab=l;this.oa()}else if(this.a.g()||this.Ab){var b=a.indexOf("|"),c=a.substring(0,b),d=a.substring(b+1);b=c.indexOf(",");if(b==-1){var e=c;this.S.send("ACK:"+e);this.ta(d)}else{var e=c.substring(0,b);this.S.send("ACK:"+e);var f=c.substring(b+1).split("/");f[0]=parseInt(f[0],10);f[1]=parseInt(f[1],10);if(f[0]==1)this.Da=[];this.Da.push(d);if(f[0]==f[1]){this.ta(this.Da.join(""));delete this.Da}}}};
K.prototype.tb=function(a){if(a==G){this.w=g;this.Tb=l;this.oa()}else if(this.a.g()){if(!this.w)return;var b=parseInt(a.split(":")[1],10);if(b==this.ea){this.w=g;this.Ga()}}};K.prototype.Ga=function(){if(this.w||!this.da.length)return;var a=this.da.shift();++this.ea;this.qb.send(this.ea+a);this.w=l};K.prototype.ta=function(a){var b=a.indexOf(":"),c=a.substr(0,b),d=a.substring(b+1);this.a.g()?this.a.j(c,d):(this.K||(this.K=[])).push({service:c,payload:d})};K.prototype.J=3800;
K.prototype.send=function(a,b){var c=a+":"+b;if(!y||b.length<=this.J)this.da.push("|"+c);else{var d=b.length,e=Math.ceil(d/this.J),f=0,h=1;while(f<d){this.da.push(","+h+"/"+e+"|"+c.substr(f,this.J));h++;f+=this.J}}this.Ga()};K.prototype.b=function(){K.p.b.call(this);var a=Xb;Ca(a,this.pb);Ca(a,this.La);this.pb=this.La=i;tb(this.D);tb(this.z);this.D=this.z=i;this.Aa=this.ia=i};
var Xb=[],Zb=function(){var a=g;try{for(var b=0,c=Xb.length;b<c;b++)a=a||Xb[b].receive()}catch(d){Xb[b].d.a.rb();if(!Xb.length)return}var e=ya();if(a)Sb=e;var f=e-Sb<1000?10:100;Tb=window.setTimeout(Yb,f)},Yb=u(Zb,K),$b=function(){Sb=ya();Tb&&window.clearTimeout(Tb);Tb=window.setTimeout(Yb,10)},Wb=function(a,b){this.Q=a;this.zb=b;this.sa=0};Wb.prototype.send=function(a){this.sa=++this.sa%2;var b=this.Q+"#"+this.sa+encodeURIComponent(a);try{if(z)this.zb.location.href=b;else this.zb.location.replace(b)}catch(c){}$b()};
var Vb=function(a,b,c){this.d=a;this.vb=b;this.Mb=c;this.Xa=this.vb.location.href.split("#")[0]+"#INITIAL";Xb.push(this);$b()};Vb.prototype.receive=function(){var a=this.vb.location.href;if(a!=this.Xa){this.Xa=a;var b=a.split("#")[1];if(b){b=b.substr(1);this.Mb(decodeURIComponent(b))}return l}else return g};var L=function(a,b){E.call(this);this.ob=b;this.r=[];this.Va(a)};v(L,E);L.prototype.V=i;L.prototype.W=i;L.prototype.G=function(a){this.V=a};L.prototype.Ja=function(a){this.W=a};L.prototype.k=function(){if(this.r.length)return this.r.pop();return this.ra()};L.prototype.v=function(a){this.r.length<this.ob?this.r.push(a):this.ua(a)};L.prototype.Va=function(a){if(a>this.ob)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var b=0;b<a;b++)this.r.push(this.ra())};
L.prototype.ra=function(){return this.V?this.V():{}};L.prototype.ua=function(a){if(this.W)this.W(a);else if(ta(a.dispose))a.dispose();else for(var b in a)delete a[b]};L.prototype.b=function(){L.p.b.call(this);var a=this.r;while(a.length)this.ua(a.pop());delete this.r};var N=function(a,b){this.type=a;this.target=b;this.currentTarget=this.target};v(N,E);N.prototype.b=function(){delete this.type;delete this.target;delete this.currentTarget};N.prototype.F=g;N.prototype.ca=l;N.prototype.stopPropagation=function(){this.F=l};N.prototype.preventDefault=function(){this.ca=g};var O=function(a,b){a&&this.init(a,b)};v(O,N);O.prototype.type=i;O.prototype.target=i;O.prototype.relatedTarget=i;O.prototype.offsetX=0;O.prototype.offsetY=0;O.prototype.clientX=0;O.prototype.clientY=0;O.prototype.screenX=0;O.prototype.screenY=0;O.prototype.button=0;O.prototype.keyCode=0;O.prototype.charCode=0;O.prototype.ctrlKey=g;O.prototype.altKey=g;O.prototype.shiftKey=g;O.prototype.metaKey=g;O.prototype.i=i;
O.prototype.init=function(a,b){this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;this.relatedTarget=a.relatedTarget?a.relatedTarget:this.type=="mouseover"?a.fromElement:this.type=="mouseout"?a.toElement:i;this.offsetX=typeof a.layerX=="number"?a.layerX:a.offsetX;this.offsetY=typeof a.layerY=="number"?a.layerY:a.offsetY;this.clientX=typeof a.clientX=="number"?a.clientX:a.pageX;this.clientY=typeof a.clientY=="number"?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(this.type=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.i=a;delete this.ca;delete this.F};O.prototype.stopPropagation=function(){this.F=l;if(this.i.stopPropagation)this.i.stopPropagation();else this.i.cancelBubble=l};
O.prototype.preventDefault=function(){this.ca=g;if(this.i.preventDefault)this.i.preventDefault();else{this.i.returnValue=g;try{this.i.keyCode=-1}catch(a){}}};O.prototype.fb=function(){return this.i};O.prototype.b=function(){O.p.b.call(this);this.i=i};var P=function(){},ac=0;P.prototype.$=i;P.prototype.listener=i;P.prototype.proxy=i;P.prototype.src=i;P.prototype.type=i;P.prototype.capture=i;P.prototype.handler=i;P.prototype.key=0;P.prototype.removed=g;P.prototype.na=g;P.prototype.init=function(a,b,c,d,e,f){if(ta(a))this.$=l;else if(a&&a.handleEvent&&ta(a.handleEvent))this.$=g;else throw Error("Invalid listener argument");this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.handler=f;this.na=g;this.key=++ac;this.removed=g};
P.prototype.handleEvent=function(a){if(this.$)return this.listener.call(this.handler||this.src,a);return this.listener.handleEvent.call(this.listener,a)};var bc={},Q={},cc={},dc=new L(0,600);dc.G(function(){return{q:0}});dc.Ja(function(a){a.q=0});var R=new L(0,600);R.G(function(){return[]});R.Ja(function(a){a.length=0;delete a.O;delete a.Ba});var ec=new L(0,600);ec.G(function(){var a=function(b){return hc.call(a.src,a.key,b)};return a});var ic=function(){return new P},jc=new L(0,600);jc.G(ic);
var kc=function(){return new O},lc=function(){var a=i;if(y){a=new L(0,600);a.G(kc)}return a},mc=lc(),nc="on",oc={},pc=function(a,b,c,d,e){if(b)if(t(b)=="array"){for(var f=0;f<b.length;f++)pc(a,b[f],c,d,e);return i}else{var h=!!d,j=Q;b in j||(j[b]=dc.k());j=j[b];if(!(h in j)){j[h]=dc.k();j.q++}j=j[h];var k=xa(a),m,o;if(j[k]){m=j[k];for(var f=0;f<m.length;f++){o=m[f];if(o.listener==c&&o.handler==e){if(o.removed)break;return m[f].key}}}else{m=j[k]=R.k();j.q++}var p=ec.k();p.src=a;o=jc.k();o.init(c,p,
a,b,h,e);var q=o.key;p.key=q;m.push(o);bc[q]=o;cc[k]||(cc[k]=R.k());cc[k].push(o);if(a.addEventListener){if(a==s||!a.Pb)a.addEventListener(b,p,h)}else a.attachEvent(qc(b),p);return q}else throw Error("Invalid event type");},rc=function(a,b,c,d,e){if(t(b)=="array"){for(var f=0;f<b.length;f++)rc(a,b[f],c,d,e);return i}var h=!!d,j=sc(a,b,h);if(!j)return g;for(var f=0;f<j.length;f++)if(j[f].listener==c&&j[f].capture==h&&j[f].handler==e)return tc(j[f].key);return g},tc=function(a){if(!bc[a])return g;var b=
bc[a];if(b.removed)return g;var c=b.src,d=b.type,e=b.proxy,f=b.capture;if(c.removeEventListener){if(c==s||!c.Pb)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(qc(d),e);var h=xa(c),j=Q[d][f][h];if(cc[h]){var k=cc[h];Ca(k,b);k.length==0&&delete cc[h]}b.removed=l;j.Ba=l;uc(d,f,h,j);delete bc[a];return l},uc=function(a,b,c,d){if(!d.O)if(d.Ba){for(var e=0,f=0;e<d.length;e++){if(d[e].removed){jc.v(d[e]);continue}if(e!=f)d[f]=d[e];f++}d.length=f;d.Ba=g;if(f==0){R.v(d);delete Q[a][b][c];Q[a][b].q--;
if(Q[a][b].q==0){dc.v(Q[a][b]);delete Q[a][b];Q[a].q--}if(Q[a].q==0){dc.v(Q[a]);delete Q[a]}}}},sc=function(a,b,c){var d=Q;if(b in d){d=d[b];if(c in d){d=d[c];var e=xa(a);if(d[e])return d[e]}}return i},qc=function(a){if(a in oc)return oc[a];return oc[a]=nc+a},wc=function(a,b,c,d){var e=1,f=Q;if(b in f){f=f[b];if(c in f){f=f[c];var h=xa(a);if(f[h]){var j=f[h];if(j.O)j.O++;else j.O=1;try{var k=j.length;for(var m=0;m<k;m++){var o=j[m];if(o&&!o.removed)e&=vc(o,d)!==g}}finally{j.O--;uc(b,c,h,j)}}}}return Boolean(e)},
vc=function(a,b){var c=a.handleEvent(b);a.na&&tc(a.key);return c},hc=function(a,b){if(!bc[a])return l;var c=bc[a],d=c.type,e=Q;if(!(d in e))return l;e=e[d];var f;if(y){var h=b||oa("window.event"),j=l in e;if(j){if(h.keyCode<0||h.returnValue!=undefined)return l;xc(h)}xa(c.src);var k=mc.k();k.init(h,this);f=l;try{if(j){var m=R.k();for(var o=k.currentTarget;o;o=o.parentNode)m.push(o);for(var p=m.length-1;!k.F&&p>=0;p--){k.currentTarget=m[p];f&=wc(m[p],d,l,k)}for(var p=0;!k.F&&p<m.length;p++){k.currentTarget=
m[p];f&=wc(m[p],d,g,k)}}else f=vc(c,k)}finally{if(m){m.length=0;R.v(m)}k.dispose();mc.v(k)}return f}var q=new O(b,this);try{f=vc(c,q)}finally{q.dispose()}return f},xc=function(a){var b=g;if(a.keyCode==0)try{a.keyCode=-1;return}catch(c){b=l}if(b||a.returnValue==undefined)a.returnValue=l};var S=function(a){this.a=a;this.Rb=this.a.c.pru;this.sb=this.a.c.ifrid;z&&yc()};v(S,I);if(z){var zc=[],Ac=0,yc=function(){Ac||(Ac=window.setTimeout(function(){Bc()},1000))},Bc=function(a){var b=ya(),c=a||3000;while(zc.length&&b-zc[0].timestamp>=c){var d=zc.shift().iframeElement;tb(d)}Ac=window.setTimeout(Cc,1000)},Cc=function(){Bc()}}S.prototype.f=3;S.prototype.connect=function(){this.send("tp","SETUP")};S.prototype.H=function(a){if(a=="SETUP"){this.send("tp",G);this.a.m()}else a==G&&this.a.m()};
S.prototype.send=function(a,b){if(y){var c=document.createElement("div");c.innerHTML='<iframe onload="this.xpcOnload()"></iframe>';var d=c.childNodes[0];d.xpcOnload=Dc}else{var d=document.createElement("iframe");z?zc.push({timestamp:ya(),iframeElement:d}):pc(d,"load",Dc)}var e=d.style;e.visibility="hidden";e.width=d.style.height="0px";e.position="absolute";var f=this.Rb;f+="#"+this.a.name;if(this.sb)f+=","+this.sb;f+="|"+a+":"+encodeURIComponent(b);d.src=f;document.body.appendChild(d)};
var Dc=function(){tb(this);this.xpcOnload=i};window.xpcRelay=function(a,b){var c=b.indexOf(":"),d=b.substring(0,c),e=b.substring(c+1);H[a].j(d,decodeURIComponent(e))};S.prototype.b=function(){S.p.b.call(this);z&&Bc(0)};var T=function(a,b){this.a=a;this.aa=b||"*"};v(T,I);T.prototype.f=1;var Ec=g,Gc=function(){if(!Ec){pc(window.postMessage?window:document,"message",Fc,g,T);Ec=l}},Fc=function(a){var b=a.fb().data,c=b.indexOf("|"),d=b.indexOf(":");if(c==-1||d==-1)return g;var e=b.substring(0,c),f=b.substring(c+1,d),h=b.substring(d+1),j=H[e];if(j){j.j(f,h);return l}for(var k in H){var m=H[k];if(m.s()==1&&!m.g()&&f=="tp"&&h=="SETUP"){m.name=e;H[e]=m;H[k]=i;m.j(f,h);return l}}return g};
T.prototype.H=function(a){switch(a){case "SETUP":if(!this.Vb){this.Vb=l;this.send("tp",G)}break;case G:this.a.m();break}};T.prototype.connect=function(){Gc();this.T()};T.prototype.T=function(){if(this.a.g())return;this.send("tp","SETUP");window.setTimeout(u(this.T,this),100)};T.prototype.send=function(a,b){var c=this.a.h;if(!c)return;var d=c.postMessage?c:c.document;this.send=function(e,f){d.postMessage(this.a.name+"|"+e+":"+f,this.aa)};this.send(a,b)};
T.prototype.b=function(){T.p.b.call(this);rc(window.postMessage?window:document,"message",Fc,g,T)};var U=function(a){this.a=a;this.Na=a.at||"";this.yb=a.rat||"";Hc();this[Ic]=this.N;this[Jc]=this.Ta};v(U,I);
var Kc="GRPC____NIXVBS_wrapper",Lc="GRPC____NIXVBS_get_wrapper",Ic="GRPC____NIXJS_handle_message",Jc="GRPC____NIXJS_create_channel",Mc="GRPC____NIXVBS_container",Hc=function(){if(window.nix_setup_complete)return;var a="Class "+Kc+"\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport."+Ic+
"(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport."+Jc+"(channel)\nEnd Sub\nPublic Sub "+Mc+"()\n End Sub\nEnd Class\n Function "+Lc+"(transport, auth)\nDim wrap\nSet wrap = New "+Kc+"\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet "+Lc+" = wrap\nEnd Function";try{window.execScript(a,"vbscript");window.nix_setup_complete=l}catch(b){}};U.prototype.f=6;U.prototype.u=g;U.prototype.o=i;U.prototype.connect=function(){this.a.s()==0?this.ka():this.ja()};
U.prototype.ka=function(){if(this.u)return;var a=this.a.t;try{a.contentWindow.opener=window[Lc](this,this.Na);this.u=l}catch(b){}this.u||window.setTimeout(u(this.ka,this),100)};U.prototype.ja=function(){if(this.u)return;try{var a=window.opener;if(a&&Mc in a){this.o=a;var b=this.o.GetAuthToken();if(b!=this.yb)return;this.o.CreateChannel(window[Lc](this,this.Na));this.u=l;this.a.m()}}catch(c){return}this.u||window.setTimeout(u(this.ja,this),100)};
U.prototype.Ta=function(a){this.o=a;var b=this.o.GetAuthToken();if(b!=this.yb)return;this.a.m()};U.prototype.N=function(a,b){function c(){this.a.j(a,b)}window.setTimeout(u(c,this),1)};U.prototype.send=function(a,b){this.o.SendMessage(a,b)};U.prototype.b=function(){U.p.b.call(this);this.o=i};var V=function(a){E.call(this);this.c=a;this.name=this.c.cn||Rb(10);this.Ia={};H[this.name]=this;pc(window,"unload",Nc)};v(V,E);V.prototype.d=i;V.prototype.ga=1;V.prototype.g=function(){return this.ga==2};V.prototype.h=i;V.prototype.t=i;V.prototype.Ka=function(a){this.h=a};
V.prototype.Wa=function(){if(this.d)return;if(!this.c.tp)if(ta(document.postMessage)||ta(window.postMessage))this.c.tp=1;else if(db)this.c.tp=2;else if(y&&this.c.pru)this.c.tp=3;else if(y)this.c.tp=6;else if(this.c.lpu&&this.c.ppu)this.c.tp=4;switch(this.c.tp){case 1:this.d=new T(this,this.c.ph);break;case 6:this.d=new U(this);break;case 2:this.d=new J(this);break;case 3:this.d=new S(this);break;case 4:this.d=new K(this);break}if(!this.d)throw Error("CrossPageChannel: No suitable transport found!");
};V.prototype.Za=g;V.prototype.Ra=g;V.prototype.connect=function(a){this.Ob=a;if(this.Za){this.Ra=l;return}if(this.c.ifrid)this.t=sa(this.c.ifrid)?document.getElementById(this.c.ifrid):this.c.ifrid;if(this.t){var b=this.t.contentWindow;b||(b=window.frames[this.c.ifrid]);this.Ka(b)}if(!this.h)if(window==top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");else this.Ka(window.parent);this.Wa();this.d.connect()};
V.prototype.close=function(){if(!this.g())return;this.ga=3;this.d.dispose();this.d=i};V.prototype.m=function(){if(this.g())return;this.ga=2;this.Ob()};V.prototype.rb=function(){this.close()};V.prototype.xb=function(a,b,c){this.Ia[a]={name:a,callback:b,jsonEncoded:!!c}};V.prototype.send=function(a,b){if(!this.g())return;if(this.h.closed){this.close();return}if(ua(b))b=Ob(b);this.d.send(a,b)};
V.prototype.j=function(a,b){if(!a||a=="tp")this.d.H(b);else if(this.g()){var c=this.Ia[a];if(c){if(c.jsonEncoded)try{b=Mb(b)}catch(d){return}c.callback(b)}}};V.prototype.s=function(){return window.parent==this.h?1:0};V.prototype.b=function(){V.p.b.call(this);this.close();this.h=i;this.t=i;delete this.Ia;H[this.name]=i};var Nc=function(){for(var a in H){var b=H[a];b&&b.dispose()}};var Oc=function(a){var b=a||document.location.protocol+"//"+document.location.host;return b+"/robots.txt"};var W=function(a,b){this.B=a.width;this.A=a.height;this.Nb=b;this.aa=this.hb(a.src,document);this.Z=g;this.e=a;this.nb(this.jb())};W.prototype.jb=function(){var a={};a.ifrid=this.e.id;a.pu=this.e.src;a.ph=this.aa;a.cn=this.Nb;a.ppu=Oc(this.aa);a.lpu=Oc();return a};W.prototype.nb=function(a){this.a=new V(a);this.a.xb("expandable_ad",u(this.N,this));this.a.connect(function(){});window.setTimeout(u(this.lb,this),30000)};
W.prototype.lb=function(){if(this.a&&!this.a.g()){this.a.d.connect=function(){};if(this.a.d.f==1)this.a.d.T=function(){};if(this.a.d.f==4)this.a.d.la=function(){};this.a.d.dispose();this.a.dispose()}};W.prototype.hb=function(a,b){var c=a.indexOf("//"),d=c>0,e=d?a.substring(0,c):b.location.protocol,f=d?a.substring(c+2):b.location.host,h=f.indexOf("/");if(h<0)h=f.indexOf("?");if(d&&h>0)f=f.substring(0,h);return e+"//"+f};
W.prototype.N=function(a){var b=a.split("_"),c=b[0];if(c=="expand")this.mb(b);else c=="collapse"&&this.kb()};W.prototype.Fa=function(a){this.a.send("expandable_ad",a)};W.prototype.mb=function(a){if(this.Z)return;var b,c;for(var d in a){var e=a[d].charAt(0);if(e=="w")b=parseInt(a[d].substring(1),10);else if(e=="h")c=parseInt(a[d].substring(1),10)}var f=this.ab(b,c);this.cb(b,c,f);this.Fa("ok_expand_w"+b+"_h"+c+"_d"+f)};
W.prototype.kb=function(){if(!this.Z)return;this.Qa();this.Fa("ok_collapse_w"+this.B+"_h"+this.A)};W.prototype.Qa=function(){this.e.style.width=this.B+"px";this.e.style.height=this.A+"px";this.e.style.left="0";this.e.style.top="0";this.e.style.zIndex=i;this.e.parentNode.style.zIndex=i;this.Z=g};
W.prototype.cb=function(a,b,c){this.e.style.position="absolute";this.e.style.width=a+"px";this.e.style.height=b+"px";this.e.style.zIndex=9999;this.e.parentNode.style.zIndex=9999;if(a>this.B&&(c==0||c==3))this.e.style.left="-"+(a-this.B)+"px";if(b>this.A&&(c==1||c==0))this.e.style.top="-"+(b-this.A)+"px";this.Z=l};
W.prototype.ab=function(a,b){var c=Db(this.e),d=rb(window),e=a-this.B,f=b-this.A,h=c.y,j=f>h,k=d.height-(c.y+this.A),m=j||k>=h,o=c.x,p=e>o,q=d.width-(c.x+this.B),w=p||q>=o,M=0;if(m&&w)M=2;else if(m&&!w)M=3;else if(!m&&w)M=1;else if(!m&&!w)M=0;return M};
var Pc=function(){},Sc=function(a,b,c,d,e){if(!a||!b||c<=0||d<=0)return i;var f=Rb(10);b=Qc(b,c,d,f);var h=Rc(a,b,c,d,e);return new W(h,f)},Qc=function(a,b,c,d){var e=kb().X();return a+(a.indexOf("?")==-1?"?":"&")+"w="+b+"&h="+c+"&xpc="+d+"&p="+escape(e.location.protocol+"//"+e.location.host)},Rc=function(a,b,c,d,e){var f='<ins style="width:'+c+"px;height:"+d+'px;position:relative;margin:0;padding:0;display:block;visibility:visible;border:none"><iframe allowtransparency=true frameborder=0 height='+
d+" hspace=0 id="+a+' marginheight=0 marginwidth=0 name=google_ads_frame scrolling=no src="'+b+'" style="left:0;position:absolute;top:0" vspace=0 width='+c+"></iframe></ins>",h=mb(),j=h.xa(e);if(j)j.innerHTML=f;else h.X().write(f);return h.xa(a)};za("ExpandableAdSlot",W);za("ExpandableAdSlotFactory",Pc);var Tc=0,Uc=g;function Vc(a){return a!=i?'"'+a+'"':'""'}function ha(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function X(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}function Y(a){var b=window,c=ba[a]||ca[a]||i,d=b[a];X(c,d)}function Z(a,b){b!=i&&X(a,ha(b))}function $(a){var b=window,c=ba[a]||ca[a]||i,d=b[a];Z(c,d)}function Wc(a,b){var c=window,d=ba[a]||ca[a]||i,e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];X(d,e)}
function Xc(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){X("u_h",b.height);X("u_w",b.width);X("u_ah",b.availHeight);X("u_aw",b.availWidth);X("u_cd",b.colorDepth)}X("u_tz",d);X("u_his",history.length);X("u_java",c);navigator.plugins&&X("u_nplug",navigator.plugins.length);navigator.mimeTypes&&X("u_nmime",navigator.mimeTypes.length)}
function Yc(a){if(!a.google_enable_first_party_cookie)return;if(n==i)n=new da;if(a._GA_googleCookieHelper==i)a._GA_googleCookieHelper=new r;if(!a._google_cookie_fetched){a._google_cookie_fetched=l;a._GA_googleCookieHelper.db(Zc(a.google_ad_client))}}function Zc(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function $c(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}
function ad(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}function bd(){var a=y&&A("6")&&!A("8"),b=db&&A("1.8.1"),c=z&&A("525");if(Za&&(a||b||c))return l;else if(Ya&&(c||b))return l;else if($a&&b)return l;return g}
function cd(a,b){var c=a.google_allow_expandable_ads;if(c!=i&&c==g||!b.body||a.google_ad_output!="html"||dd(a,b)||ed(a)||fd(a.google_ad_format)||typeof a.google_ad_height!="number"&&String(parseInt(a.google_ad_height,10))!=a.google_ad_height||typeof a.google_ad_width!="number"&&String(parseInt(a.google_ad_width,10))!=a.google_ad_width||!bd())return g;return l}
function gd(){var a=Math.random(),b=0,c=ia("0.03",0.03),d=2*c;if(a<c)return 30143019;if(a<d)return 30143020;b=d;c=ia("0.03",0.03);d=2*c;c+=b;d+=b;if(a<c)return 30143021;if(a<d)return 30143022;return 0}function hd(a){a.google_allow_expandable_ads=g;a.google_expandable_iframe=g}var id=Math.random()<0.0010;function jd(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}
function kd(a,b,c,d){var e=ad(a);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+Vc(ld(c))+"></"+f+">");else if(a.google_ad_output=="html")if(b.body&&(a.google_expandable_iframe||Tc==30143020)){var h=a.google_container_id||d||i;a["google_expandable_ad_slot"+e]=Sc("google_ads_frame"+e,ld(c),parseInt(a.google_ad_width,10),
parseInt(a.google_ad_height,10),h)}else{var j='<iframe name="google_ads_frame" width='+Vc(a.google_ad_width)+" height="+Vc(a.google_ad_height)+" frameborder="+Vc(a.google_ad_frameborder)+" src="+Vc(ld(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';if(Uc&&Tc==30143022)j='<ins style="width:'+parseInt(a.google_ad_width,10)+"px;height:"+parseInt(a.google_ad_height,10)+'px;position:relative;margin:0;padding:0;display:block;visibility:visible;border:none">'+
j+"</ins>";a.google_container_id?md(a.google_container_id,b,j):b.write(j)}else a.google_ad_output=="textlink"&&b.write("<"+f+' language="JavaScript1.1" src='+Vc(ld(c))+"></"+f+">");if(id){var k=nd(a)+"/pagead/gen_204?id=ifjs2&token="+a.google_correlator+"&output="+ha(a.google_ad_output)+"&url="+ha(a.google_page_url);jd(a,k)}}
function od(a){for(var b in ba)a[b]=i;for(var b in ca){if(b=="google_correlator")continue;a[b]=i}a.google_allow_expandable_ads=i;a.google_container_id=i;a.google_expandable_iframe=i}function ed(a){if(a.google_ad_format)return a.google_ad_format.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function fd(a){return a&&a.indexOf("_sdo")!=-1}
function pd(a){var b=i,c=window,d=document,e=aa,f=c.google_ad_format,h=nd(c),j;if(c.google_cpa_choice!=b){c.google_ad_url=h+"/cpa/ads?";j=escape(Zc(c.google_ad_client));c.google_ad_region="_google_cpa_region_";Y("google_cpa_choice");if(typeof d.characterSet!="undefined")Z("oe",d.characterSet);else typeof d.charset!="undefined"&&Z("oe",d.charset)}else if(fd(f)){c.google_ad_url=h+"/pagead/sdo?";j=escape($c(c.google_ad_client))}else{c.google_ad_url=h+"/pagead/ads?";j=escape(Zc(c.google_ad_client))}c.google_ad_url+=
"client="+j;Y("google_ad_host");Y("google_ad_host_tier_id");var k=c.google_num_slots_by_client,m=c.google_num_slots_by_channel,o=c.google_prev_ad_formats_by_region,p=c.google_prev_ad_slotnames_by_region;if(c.google_ad_region==b&&c.google_ad_section!=b)c.google_ad_region=c.google_ad_section;var q=c.google_ad_region==b?"":c.google_ad_region;if(fd(f)){c.google_num_sdo_slots=c.google_num_sdo_slots?c.google_num_sdo_slots+1:1;if(c.google_num_sdo_slots>4)return g}else if(ed(c)){c.google_num_0ad_slots=c.google_num_0ad_slots?
c.google_num_0ad_slots+1:1;if(c.google_num_0ad_slots>3)return g}else if(c.google_cpa_choice==b){c.google_num_ad_slots=c.google_num_ad_slots?c.google_num_ad_slots+1:1;if(c.google_num_slots_to_rotate){o[q]=b;p[q]=b;if(c.google_num_slot_to_show==b)c.google_num_slot_to_show=e%c.google_num_slots_to_rotate+1;if(c.google_num_slot_to_show!=c.google_num_ad_slots)return g}else if(c.google_num_ad_slots>6&&q=="")return g}X("dt",aa);Y("google_language");c.google_country?Y("google_country"):Y("google_gl");Y("google_region");
$("google_city");$("google_hints");Y("google_safe");Y("google_encoding");Y("google_last_modified_time");$("google_alternate_ad_url");Y("google_alternate_color");Y("google_skip");Y("google_targeting");var w=c.google_ad_client;if(k[w])k[w]+=1;else{k[w]=1;k.length+=1}if(o[q])if(!fd(f)){Z("prev_fmts",o[q].toLowerCase());k.length>1&&X("slot",k[w])}p[q]&&Z("prev_slotnames",p[q].toLowerCase());if(f&&!c.google_ad_slot){Z("format",f.toLowerCase());fd(f)||(o[q]=o[q]?o[q]+","+f:f)}if(c.google_ad_slot)p[q]=p[q]?
p[q]+","+c.google_ad_slot:c.google_ad_slot;Y("google_max_num_ads");X("output",c.google_ad_output);Y("google_adtest");Y("google_ad_callback");Y("google_ad_slot");$("google_correlator");c.google_new_domain_checked==1&&c.google_new_domain_enabled==0&&X("dblk",1);if(c.google_ad_channel){$("google_ad_channel");var M="",fc=c.google_ad_channel.split(qd);for(var eb=0;eb<fc.length;eb++){var fb=fc[eb];if(m[fb])M+=fb+"+";else m[fb]=1}Z("pv_ch",M)}if(c.google_ad_host_channel){$("google_ad_host_channel");var xd=
rd(c.google_ad_host_channel,c.google_viewed_host_channels);Z("pv_h_ch",xd)}c.google_enable_first_party_cookie&&Z("cookie",c._GA_googleCookieHelper.ib());$("google_page_url");Wc("google_color_bg",e);Wc("google_color_text",e);Wc("google_color_link",e);Wc("google_color_url",e);Wc("google_color_border",e);Wc("google_color_line",e);c.google_reuse_colors?X("reuse_colors",1):X("reuse_colors",0);Y("google_kw_type");$("google_kw");$("google_contents");Y("google_num_radlinks");Y("google_max_radlink_len");Y("google_rl_filtering");
Y("google_rl_mode");Y("google_rt");$("google_rl_dest_url");Y("google_num_radlinks_per_unit");Y("google_ad_type");Y("google_image_size");Y("google_ad_region");Uc=cd(c,d);if(!Uc)hd(c);else if(c.google_expandable_iframe===g)hd(c);else if(j in{"ca-pub-2944451727872625":1,"ca-pub-9483266128490610":1,"ca-pub-1955924717845427":1,"ca-pub-6664249124335298":1})c.google_expandable_iframe=l;else if(!(c.google_expandable_iframe==l)){Tc=gd();X("eid",Tc);hd(c)}var gc=c.google_allow_expandable_ads;if(gc!=i)gc?X("ea",
"1"):X("ea","0");Y("google_feedback");$("google_referrer_url");$("google_page_location");X("frm",c.google_iframing);Y("google_bid");Y("google_ctr_threshold");Y("google_cust_age");Y("google_cust_gender");Y("google_cust_interests");Y("google_cust_id");Y("google_cust_job");Y("google_cust_u_url");Y("google_cust_l");Y("google_cust_lh");Y("google_cust_ch");Y("google_ed");Y("google_video_doc_id");Y("google_video_product_type");$("google_ui_features");$("google_only_ads_with_video");$("google_disable_video_autoplay");
if(a){Z("ff",Eb(a));var gb=Cb(a),hb=rb();if(gb&&hb){Z("biw",hb.width);Z("bih",hb.height);Z("adx",gb.x);Z("ady",gb.y)}}Gb();X("ga_vid",c.gaGlobal.vid);X("ga_sid",c.gaGlobal.sid);X("ga_hid",c.gaGlobal.hid);X("ga_fc",c.gaGlobal.from_cookie);$("google_analytics_uacct");Y("google_ad_override");Y("google_flash_version");Xc(c);id&&X("gen_204","ifjs2");return l}
function rd(a,b){var c=a.split("|"),d=-1,e=[];for(var f=0;f<c.length;f++){var h=c[f].split(qd);b[f]||(b[f]={});var j="";for(var k=0;k<h.length;k++){var m=h[k];if(b[f][m])j+="+"+m;else b[f][m]=1}j=j.slice(1);e[f]=j;if(j!="")d=f}var o="";if(d>-1){for(var f=0;f<d;f++)o+=e[f]+"|";o+=e[d]}return o}
function sd(){var a=window,b=document;Yc(a);var c;if(Math.random()<0.01){var d="google_temp_span";if(!ob(d)){b.write("<span id="+d+"></span>");c=ob(d)}}var e=pd(c);c&&tb(c);if(!e)return;kd(a,b,a.google_ad_url);od(a)}function ld(a){var b=(new Date).getTime()-aa,c="&dtd="+(b<1000?b:"M");return a+c}function td(){sd();return l}
function dd(a,b){if(a.top.location==b.location)return g;var c=b.documentElement;if(a.google_ad_width&&a.google_ad_height){var d=1,e=1;if(a.innerHeight){d=a.innerWidth;e=a.innerHeight}else if(c&&c.clientHeight){d=c.clientWidth;e=c.clientHeight}else if(b.body){d=b.body.clientWidth;e=b.body.clientHeight}if(e>2*a.google_ad_height||d>2*a.google_ad_width)return g}return l}
function ud(a){var b=window,c=i,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if(fd(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html")b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;vd(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=aa;if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot={};if(b.google_flash_version==
c)b.google_flash_version=ja();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function wd(a){if(a in yd)return yd[a];return yd[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var yd={};function ka(){return wd("msie")&&!window.opera}
function zd(a){var b={},c=a.split("?"),d=c[c.length-1].split("&");for(var e=0;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(h){}}return b}function Ad(){var a=window,b=zd(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}function Bd(a,b){for(var c in b)a["google_"+c]=b[c]}
function Cd(a,b){if(!b)return a.location;return a.referrer}function Dd(a,b){if(!b&&a.google_referrer_url==i)return"0";else if(b&&a.google_referrer_url==i)return"1";else if(!b&&a.google_referrer_url!=i)return"2";else if(b&&a.google_referrer_url!=i)return"3";return"4"}function Ed(a,b,c,d){a.page_url=Cd(c,d);a.page_location=i}function Fd(a,b,c,d){a.page_url=b.google_page_url;a.page_location=Cd(c,d)||"EMPTY"}
function Gd(a,b){var c={},d=dd(a,b);c.iframing=Dd(a,d);!!a.google_page_url?Fd(c,a,b,d):Ed(c,a,b,d);c.last_modified_time=b.location==c.page_url?Date.parse(b.lastModified)/1000:i;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function Hd(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=i;b.page_url=c;b.page_location=a.location;b.last_modified_time=i;b.referrer_url=c;return b}
function vd(a,b){var c;c=a.google_page_url==i&&Id[b.domain]?Hd(b):Gd(a,b);Bd(a,c)}function md(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var Id={};Id["ad.yieldmanager.com"]=l;var qd=/[+, ]/;window.google_render_ad=sd;var Jd={google:1,googlegroups:1,gmail:1,googlemail:1,orkut:1,googleimages:1,googleprint:1};function Kd(a){var b=a.google_page_location||a.google_page_url;if(!b)return g;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=g;if(e.length>=3)f=e[e.length-3]in Jd;if(e.length>=2)f=f||e[e.length-2]in Jd;return f}
function Ld(a,b,c){if(a.google_new_domain_checked==0){var d=Math.random();if(d<c){var e="http://googleads.g.doubleclick.net/pagead/test_domain.js",f="script";b.write("<"+f+' src="'+e+'"></'+f+">");a.google_new_domain_checked=1;return l}}return g}function nd(a){var b="http://googleads.g.doubleclick.net",c="http://pagead2.googlesyndication.com";if(!Kd(a)&&a.google_new_domain_enabled==1)return b;return c};function Md(a,b){var c="script",d=Ld(a,b,ia("1",0.01));d&&ka()?b.write("<"+c+' src="http://pagead2.googlesyndication.com/pagead/render_ads.js"></'+c+">"):b.write("<"+c+">window.google_render_ad();</"+c+">")}Ad();ud(td);Md(window,document);
})()
